import "server-only";

import type { PrismaClient } from "@/generated/prisma/client";
import type { ApplicationContext } from "@/domains/application/context";
import type { LeadReader, PatientReader } from "@/domains/application/readers";
import { normalizePage, parseDateRange } from "@/domains/application/query";
import { mapAppointmentStatus, toDateOnly, toIso } from "@/domains/application/mappers";
import type { LeadListItem, LeadStageType, PatientDetails, PatientTimelineItem } from "@/domains/application/view-models";
import { getPrismaClient } from "@/lib/db";

const stageType = (value: string) => value.toLowerCase() as LeadStageType;
const page = <T,>(items:T[],total:number,offset:number,limit:number)=>({items,page:{offset,limit,total,hasMore:offset+items.length<total}});
const leadSelect={id:true,name:true,phoneE164:true,emailNormalized:true,source:true,estimatedValueCents:true,patientId:true,pipelineId:true,clinicId:true,stageId:true,createdAt:true,updatedAt:true,wonAt:true,lostAt:true,stage:{select:{name:true,type:true}},pipeline:{select:{name:true}},clinic:{select:{name:true}},assignedMembership:{select:{id:true,user:{select:{displayName:true}}}}} as const;
type LeadRow={id:string;name:string;phoneE164:string|null;emailNormalized:string|null;source:string|null;estimatedValueCents:number;patientId:string|null;pipelineId:string;clinicId:string|null;stageId:string;createdAt:Date;updatedAt:Date;wonAt:Date|null;lostAt:Date|null;stage:{name:string;type:string};pipeline:{name:string};clinic:{name:string}|null;assignedMembership:{id:string;user:{displayName:string}}|null};
function mapLead(row:LeadRow):LeadListItem{return {id:row.id,name:row.name,phone:row.phoneE164,email:row.emailNormalized,source:row.source,estimatedValueCents:row.estimatedValueCents,stageId:row.stageId,stageName:row.stage.name,stageType:stageType(row.stage.type),clinicId:row.clinicId,clinicName:row.clinic?.name??null,assignee:row.assignedMembership?{id:row.assignedMembership.id,name:row.assignedMembership.user.displayName}:null,patientId:row.patientId,createdAt:toIso(row.createdAt),updatedAt:toIso(row.updatedAt)}}

export class PrismaLeadReader implements LeadReader {
 constructor(private readonly context:ApplicationContext,private readonly prisma:PrismaClient=getPrismaClient()){}
 async list(query:Parameters<LeadReader["list"]>[0]={}){const {offset,limit}=normalizePage(query);const range=query.range?parseDateRange(query.range):null;const where={tenantId:this.context.tenantId,archivedAt:null,...(query.search?{OR:[{name:{contains:query.search,mode:"insensitive" as const}},{phoneE164:{contains:query.search}},{emailNormalized:{contains:query.search.toLowerCase(),mode:"insensitive" as const}}]}:{}),...(query.stageId?{stageId:query.stageId}:{}),...(query.assigneeId?{assignedMembershipId:query.assigneeId}:{}),...(query.clinicId?{clinicId:query.clinicId}:{}),...(query.source?{source:query.source}:{}),...(range?{createdAt:{gte:range.from,lt:range.to}}:{})};const [rows,total]=await this.prisma.$transaction([this.prisma.lead.findMany({where,select:leadSelect,orderBy:[{updatedAt:"desc"},{id:"asc"}],skip:offset,take:limit}),this.prisma.lead.count({where})]);return page(rows.map(mapLead),total,offset,limit)}
 async findById(id:string){const row=await this.prisma.lead.findFirst({where:{id,tenantId:this.context.tenantId},select:{...leadSelect,stageHistory:{select:{id:true,changedAt:true,reason:true,fromStage:{select:{name:true}},toStage:{select:{name:true}},changedBy:{select:{user:{select:{displayName:true}}}}},orderBy:[{changedAt:"desc"},{id:"desc"}]}}});return row?{...mapLead(row),pipelineId:row.pipelineId,pipelineName:row.pipeline.name,wonAt:row.wonAt?toIso(row.wonAt):null,lostAt:row.lostAt?toIso(row.lostAt):null,activities:row.stageHistory.map(x=>({id:x.id,fromStage:x.fromStage?.name??null,toStage:x.toStage.name,occurredAt:toIso(x.changedAt),reason:x.reason,owner:x.changedBy?.user.displayName??null}))}:null}
 async pipeline(){const stages=await this.prisma.pipelineStage.findMany({where:{tenantId:this.context.tenantId,active:true,pipeline:{active:true}},select:{id:true,pipelineId:true,name:true,position:true,type:true,currentLeads:{where:{tenantId:this.context.tenantId,archivedAt:null},select:leadSelect,orderBy:[{updatedAt:"desc"},{id:"asc"}],take:100}},orderBy:[{pipelineId:"asc"},{position:"asc"},{id:"asc"}]});return stages.map(s=>({id:s.id,pipelineId:s.pipelineId,name:s.name,position:s.position,type:stageType(s.type),leads:s.currentLeads.map(mapLead)}))}
 async assignees(){const rows=await this.prisma.membership.findMany({where:{tenantId:this.context.tenantId,status:"ACTIVE"},select:{id:true,user:{select:{displayName:true}}},orderBy:[{user:{displayName:"asc"}},{id:"asc"}],take:100});return rows.map(x=>({id:x.id,name:x.user.displayName}))}
 async metrics(){const rows=await this.prisma.lead.findMany({where:{tenantId:this.context.tenantId,archivedAt:null},select:{estimatedValueCents:true,stage:{select:{type:true}}},take:1000});return rows.reduce((m,x)=>{m.total++;m[x.stage.type.toLowerCase() as "open"|"won"|"lost"]++;m.estimatedValueCents+=x.estimatedValueCents;return m},{total:0,open:0,won:0,lost:0,estimatedValueCents:0})}
}

export class PrismaPatientReader implements PatientReader {
 constructor(private readonly context:ApplicationContext,private readonly prisma:PrismaClient=getPrismaClient()){}
 async list(query:Parameters<PatientReader["list"]>[0]={}){const {offset,limit}=normalizePage(query);const where={tenantId:this.context.tenantId,...(query.archived===undefined?{}:{archivedAt:query.archived?{not:null}:null}),...(query.search?{OR:[{name:{contains:query.search,mode:"insensitive" as const}},{phoneE164:{contains:query.search}},{emailNormalized:{contains:query.search.toLowerCase(),mode:"insensitive" as const}}]}:{})};const select={id:true,name:true,phoneE164:true,emailNormalized:true,birthDate:true,archivedAt:true,createdAt:true,updatedAt:true,appointments:{where:{tenantId:this.context.tenantId,startsAt:{gte:new Date()}},select:{startsAt:true},orderBy:{startsAt:"asc" as const},take:1},_count:{select:{appointments:true}}};const [rows,total]=await this.prisma.$transaction([this.prisma.patient.findMany({where,select,orderBy:[{name:"asc"},{id:"asc"}],skip:offset,take:limit}),this.prisma.patient.count({where})]);return page(rows.map(x=>({id:x.id,name:x.name,contact:{phone:x.phoneE164,email:x.emailNormalized},birthDate:toDateOnly(x.birthDate),archived:Boolean(x.archivedAt),createdAt:toIso(x.createdAt),updatedAt:toIso(x.updatedAt),nextAppointmentAt:x.appointments[0]?toIso(x.appointments[0].startsAt):null,appointmentCount:x._count.appointments})),total,offset,limit)}
 async findById(id:string):Promise<PatientDetails|null>{const row=await this.prisma.patient.findFirst({where:{id,tenantId:this.context.tenantId},select:{id:true,name:true,phoneE164:true,emailNormalized:true,birthDate:true,archivedAt:true,createdAt:true,updatedAt:true,leads:{where:{tenantId:this.context.tenantId},select:{id:true,name:true,createdAt:true}},appointments:{where:{tenantId:this.context.tenantId},select:{id:true,startsAt:true,endsAt:true,status:true,priceCents:true,clinic:{select:{name:true}},professionalClinic:{select:{professional:{select:{name:true}}}},procedure:{select:{name:true}}},orderBy:[{startsAt:"desc"},{id:"desc"}],take:100},treatmentPlans:{where:{tenantId:this.context.tenantId},select:{id:true,title:true,createdAt:true}},conversations:{where:{tenantId:this.context.tenantId},select:{id:true,channel:true,createdAt:true}},_count:{select:{appointments:true,treatmentPlans:true,conversations:true}}}});if(!row)return null;const appointments=row.appointments.map(x=>({id:x.id,startsAt:toIso(x.startsAt),endsAt:toIso(x.endsAt),status:mapAppointmentStatus(x.status),clinicName:x.clinic.name,professionalName:x.professionalClinic.professional.name,procedureName:x.procedure?.name??null,priceCents:x.priceCents}));const timeline:PatientTimelineItem[]=[{id:`patient-${row.id}`,type:"created",occurredAt:toIso(row.createdAt),title:"Paciente cadastrado",details:"Cadastro criado no FlipSchedule."},...row.leads.map(x=>({id:`lead-${x.id}`,type:"lead" as const,occurredAt:toIso(x.createdAt),title:"Lead relacionado",details:x.name})),...row.appointments.map(x=>({id:`appointment-${x.id}`,type:"appointment" as const,occurredAt:toIso(x.startsAt),title:"Agendamento",details:`${x.clinic.name} · ${mapAppointmentStatus(x.status)}`})),...row.treatmentPlans.map(x=>({id:`plan-${x.id}`,type:"treatment_plan" as const,occurredAt:toIso(x.createdAt),title:"Orçamento",details:x.title})),...row.conversations.map(x=>({id:`conversation-${x.id}`,type:"conversation" as const,occurredAt:toIso(x.createdAt),title:"Conversa",details:x.channel}))];timeline.sort((a,b)=>b.occurredAt.localeCompare(a.occurredAt));return {id:row.id,name:row.name,contact:{phone:row.phoneE164,email:row.emailNormalized},birthDate:toDateOnly(row.birthDate),archived:Boolean(row.archivedAt),createdAt:toIso(row.createdAt),updatedAt:toIso(row.updatedAt),nextAppointmentAt:appointments.filter(x=>new Date(x.startsAt)>=new Date()).sort((a,b)=>a.startsAt.localeCompare(b.startsAt))[0]?.startsAt??null,appointmentCount:row._count.appointments,address:{available:false as const},appointments,timeline,treatmentPlanCount:row._count.treatmentPlans,conversationCount:row._count.conversations,leadIds:row.leads.map(x=>x.id)}}
 async duplicates(input:{phone?:string;email?:string;excludeId?:string}){if(!input.phone&&!input.email)return [];const rows=await this.prisma.patient.findMany({where:{tenantId:this.context.tenantId,...(input.excludeId?{id:{not:input.excludeId}}:{}),OR:[...(input.phone?[{phoneE164:input.phone}]:[]),...(input.email?[{emailNormalized:input.email.toLowerCase()}]:[])]},select:{id:true,name:true,phoneE164:true,emailNormalized:true},orderBy:[{name:"asc"},{id:"asc"}],take:10});return rows.map(x=>({id:x.id,name:x.name,matchedBy:x.phoneE164===input.phone?"phone" as const:"email" as const}))}
}
