import "server-only";

import { z } from "zod";
import type { PrismaClient } from "@/generated/prisma/client";
import type { ApplicationContext, MembershipRole } from "@/domains/application/context";
import { actionFailure, type ActionResult } from "@/domains/application/actions";
import { getPrismaClient } from "@/lib/db";

type Tx=Omit<PrismaClient,"$connect"|"$disconnect"|"$on"|"$transaction"|"$extends">;
const allowed=new Set<MembershipRole>(["OWNER","MANAGER","RECEPTIONIST"]);const uuid=z.string().uuid();const optionalText=z.string().trim().max(160).nullable().default(null);const contact=z.object({name:z.string().trim().min(2).max(120),phoneE164:z.string().regex(/^\+[1-9]\d{7,14}$/).nullable().default(null),emailNormalized:z.string().trim().email().toLowerCase().nullable().default(null)});
const fail=(error:z.ZodError):ActionResult<never>=>actionFailure("VALIDATION_ERROR","Revise os campos informados.",Object.fromEntries(Object.entries(error.flatten().fieldErrors).filter((x):x is [string,string[]]=>Boolean(x[1]))));
abstract class Service {constructor(protected context:ApplicationContext,protected prisma:PrismaClient=getPrismaClient()){} protected denied(){return allowed.has(this.context.membershipRole)?null:actionFailure("ACCESS_DENIED","Você não tem permissão para esta ação.")} protected audit(tx:Tx,action:string,type:string,id:string){return tx.auditLog.create({data:{tenantId:this.context.tenantId,actorUserId:this.context.userId,actorMembershipId:this.context.membershipId,action,resourceType:type,resourceId:id,outcome:"SUCCESS"},select:{id:true}})} protected unavailable(){return actionFailure("UNAVAILABLE","Não foi possível concluir a operação. Tente novamente.")}}

const patientInput=contact.extend({birthDate:z.coerce.date().nullable().default(null),archived:z.boolean().default(false)});
export class PatientService extends Service {
 async create(input:unknown){const denied=this.denied();if(denied)return denied;const p=patientInput.safeParse(input);if(!p.success)return fail(p.error);try{return await this.prisma.$transaction(async tx=>{const duplicate=await tx.patient.findFirst({where:{tenantId:this.context.tenantId,OR:[...(p.data.phoneE164?[{phoneE164:p.data.phoneE164}]:[]),...(p.data.emailNormalized?[{emailNormalized:p.data.emailNormalized}]:[])]},select:{id:true}});if(duplicate)return actionFailure("CONFLICT","Já existe um possível paciente duplicado. Revise telefone e e-mail.");const row=await tx.patient.create({data:{tenantId:this.context.tenantId,name:p.data.name,phoneE164:p.data.phoneE164,emailNormalized:p.data.emailNormalized,birthDate:p.data.birthDate,archivedAt:p.data.archived?new Date():null},select:{id:true,name:true}});await this.audit(tx,"patient.create","Patient",row.id);return {ok:true,data:row} as const})}catch{return this.unavailable()}}
 async update(id:string,input:unknown){const denied=this.denied();if(denied)return denied;const p=patientInput.safeParse(input);if(!p.success)return fail(p.error);try{return await this.prisma.$transaction(async tx=>{if(!await tx.patient.findFirst({where:{id,tenantId:this.context.tenantId},select:{id:true}}))return actionFailure("NOT_FOUND","Paciente não encontrado.");const duplicate=await tx.patient.findFirst({where:{tenantId:this.context.tenantId,id:{not:id},OR:[...(p.data.phoneE164?[{phoneE164:p.data.phoneE164}]:[]),...(p.data.emailNormalized?[{emailNormalized:p.data.emailNormalized}]:[])]},select:{id:true}});if(duplicate)return actionFailure("CONFLICT","Já existe um possível paciente duplicado.");await tx.patient.update({where:{id},data:{name:p.data.name,phoneE164:p.data.phoneE164,emailNormalized:p.data.emailNormalized,birthDate:p.data.birthDate,archivedAt:p.data.archived?new Date():null}});await this.audit(tx,"patient.update","Patient",id);return {ok:true,data:{id}} as const})}catch{return this.unavailable()}}
}

const leadInput=contact.extend({pipelineId:uuid,stageId:uuid,clinicId:uuid.nullable().default(null),assignedMembershipId:uuid.nullable().default(null),estimatedValueCents:z.number().int().nonnegative().default(0),source:optionalText});
export class LeadService extends Service {
 private async refs(tx:Tx,p:z.infer<typeof leadInput>){const [stage,clinic,assignee]=await Promise.all([tx.pipelineStage.findFirst({where:{id:p.stageId,tenantId:this.context.tenantId,pipelineId:p.pipelineId,active:true},select:{id:true}}),p.clinicId?tx.clinic.findFirst({where:{id:p.clinicId,tenantId:this.context.tenantId},select:{id:true}}):true,p.assignedMembershipId?tx.membership.findFirst({where:{id:p.assignedMembershipId,tenantId:this.context.tenantId,status:"ACTIVE"},select:{id:true}}):true]);return Boolean(stage&&clinic&&assignee)}
 async create(input:unknown){const denied=this.denied();if(denied)return denied;const p=leadInput.safeParse(input);if(!p.success)return fail(p.error);try{return await this.prisma.$transaction(async tx=>{if(!await this.refs(tx,p.data))return actionFailure("NOT_FOUND","Pipeline, etapa, unidade ou responsável não encontrado.");const row=await tx.lead.create({data:{tenantId:this.context.tenantId,...p.data},select:{id:true}});await tx.leadStageHistory.create({data:{tenantId:this.context.tenantId,leadId:row.id,toStageId:p.data.stageId,changedByMembershipId:this.context.membershipId,reason:"Lead criado"}});await this.audit(tx,"lead.create","Lead",row.id);return {ok:true,data:row} as const})}catch{return this.unavailable()}}
 async update(id:string,input:unknown){const denied=this.denied();if(denied)return denied;const p=leadInput.safeParse(input);if(!p.success)return fail(p.error);try{return await this.prisma.$transaction(async tx=>{const old=await tx.lead.findFirst({where:{id,tenantId:this.context.tenantId},select:{stageId:true}});if(!old)return actionFailure("NOT_FOUND","Lead não encontrado.");if(!await this.refs(tx,p.data))return actionFailure("NOT_FOUND","Pipeline, etapa, unidade ou responsável não encontrado.");await tx.lead.update({where:{id},data:p.data});if(old.stageId!==p.data.stageId)await tx.leadStageHistory.create({data:{tenantId:this.context.tenantId,leadId:id,fromStageId:old.stageId,toStageId:p.data.stageId,changedByMembershipId:this.context.membershipId,reason:"Etapa alterada na edição"}});await this.audit(tx,"lead.update","Lead",id);return {ok:true,data:{id}} as const})}catch{return this.unavailable()}}
 async move(id:string,input:unknown){const denied=this.denied();if(denied)return denied;const p=z.object({stageId:uuid,reason:z.string().trim().min(2).max(240).nullable().default(null)}).safeParse(input);if(!p.success)return fail(p.error);try{return await this.prisma.$transaction(async tx=>{const lead=await tx.lead.findFirst({where:{id,tenantId:this.context.tenantId},select:{stageId:true,pipelineId:true,patientId:true}});if(!lead)return actionFailure("NOT_FOUND","Lead não encontrado.");const stage=await tx.pipelineStage.findFirst({where:{id:p.data.stageId,tenantId:this.context.tenantId,pipelineId:lead.pipelineId,active:true},select:{type:true}});if(!stage)return actionFailure("NOT_FOUND","Etapa não encontrada.");if(lead.patientId&&stage.type!=="WON")return actionFailure("CONFLICT","Um lead convertido não pode ser reaberto.");await tx.lead.update({where:{id},data:{stageId:p.data.stageId,wonAt:stage.type==="WON"?new Date():null,lostAt:stage.type==="LOST"?new Date():null}});await tx.leadStageHistory.create({data:{tenantId:this.context.tenantId,leadId:id,fromStageId:lead.stageId,toStageId:p.data.stageId,changedByMembershipId:this.context.membershipId,reason:p.data.reason}});await this.audit(tx,stage.type==="LOST"?"lead.lost":stage.type==="OPEN"?"lead.reopened":"lead.stage-change","Lead",id);return {ok:true,data:{id}} as const})}catch{return this.unavailable()}}
 async convert(id:string){const denied=this.denied();if(denied)return denied;try{return await this.prisma.$transaction(async tx=>{const lead=await tx.lead.findFirst({where:{id,tenantId:this.context.tenantId},select:{id:true,name:true,phoneE164:true,emailNormalized:true,source:true,patientId:true,pipelineId:true,stageId:true}});if(!lead)return actionFailure("NOT_FOUND","Lead não encontrado.");if(lead.patientId)return {ok:true,data:{id,patientId:lead.patientId}} as const;const duplicate=await tx.patient.findFirst({where:{tenantId:this.context.tenantId,OR:[...(lead.phoneE164?[{phoneE164:lead.phoneE164}]:[]),...(lead.emailNormalized?[{emailNormalized:lead.emailNormalized}]:[])]},select:{id:true}});if(duplicate)return actionFailure("CONFLICT","Existe um possível paciente duplicado. Vincule-o após revisão manual.");const won=await tx.pipelineStage.findFirst({where:{tenantId:this.context.tenantId,pipelineId:lead.pipelineId,type:"WON",active:true},select:{id:true},orderBy:[{position:"asc"},{id:"asc"}]});if(!won)return actionFailure("CONFLICT","O pipeline não possui uma etapa de ganho ativa.");const patient=await tx.patient.create({data:{tenantId:this.context.tenantId,name:lead.name,phoneE164:lead.phoneE164,emailNormalized:lead.emailNormalized},select:{id:true}});await tx.patientAttribution.create({data:{tenantId:this.context.tenantId,patientId:patient.id,leadId:id,source:lead.source,attributedAt:new Date()}});await tx.lead.update({where:{id},data:{patientId:patient.id,stageId:won.id,wonAt:new Date(),lostAt:null}});await tx.leadStageHistory.create({data:{tenantId:this.context.tenantId,leadId:id,fromStageId:lead.stageId,toStageId:won.id,changedByMembershipId:this.context.membershipId,reason:"Convertido em paciente"}});await this.audit(tx,"lead.convert","Lead",id);await this.audit(tx,"patient.create-from-lead","Patient",patient.id);return {ok:true,data:{id,patientId:patient.id}} as const},{isolationLevel:"Serializable"})}catch{return this.unavailable()}}
}
