import "server-only";

import { z } from "zod";
import type { PrismaClient } from "@/generated/prisma/client";
import type { AppointmentStatus as DbAppointmentStatus } from "@/generated/prisma/client";
import type { ApplicationContext } from "@/domains/application/context";
import { hasPermission } from "@/domains/application/rbac";
import { actionFailure, type ActionResult } from "@/domains/application/actions";
import { mapAppointmentStatus } from "@/domains/application/mappers";
import type { AppointmentStatus } from "@/domains/application/view-models";
import { getPrismaClient } from "@/lib/db";

const uuid = z.string().uuid();
const label = z.string().trim().min(2).max(120);
const auditSelect = { id: true } as const;
type Tx = Omit<PrismaClient, "$connect" | "$disconnect" | "$on" | "$transaction" | "$extends">;

function validation(error: z.ZodError): ActionResult<never> { return actionFailure("VALIDATION_ERROR", "Revise os campos informados.", Object.fromEntries(Object.entries(error.flatten().fieldErrors).filter((entry): entry is [string, string[]] => Boolean(entry[1])))); }
function unavailable(): ActionResult<never> { return actionFailure("UNAVAILABLE", "Não foi possível concluir a operação. Tente novamente."); }

abstract class TenantService {
  protected readonly prisma: PrismaClient;
  constructor(protected readonly context: ApplicationContext, prisma?: PrismaClient) { this.prisma = prisma ?? getPrismaClient(); }
  protected denied<T>(): ActionResult<T> | null { return (["clinics.manage", "professionals.manage", "procedures.manage", "schedule.manage", "patients.manage"] as const).some((permission) => hasPermission(this.context.membershipRole, permission)) ? null : actionFailure("ACCESS_DENIED", "Você não tem permissão para esta ação."); }
  protected audit(tx: Tx, action: string, resourceType: string, resourceId: string) { return tx.auditLog.create({ data: { tenantId: this.context.tenantId, actorUserId: this.context.userId, actorMembershipId: this.context.membershipId, action, resourceType, resourceId, outcome: "SUCCESS" }, select: auditSelect }); }
}

const clinicSchema = z.object({ name: label, slug: z.string().trim().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(80), timezoneOverride: z.string().trim().max(80).nullable().default(null), active: z.boolean().default(true) });
export class ClinicService extends TenantService {
  async create(input: unknown) { const denied=this.denied(); if(denied)return denied; const p=clinicSchema.safeParse(input); if(!p.success)return validation(p.error); try { return await this.prisma.$transaction(async tx=>{const row=await tx.clinic.create({data:{tenantId:this.context.tenantId,name:p.data.name,slug:p.data.slug,timezoneOverride:p.data.timezoneOverride,status:p.data.active?"ACTIVE":"INACTIVE"},select:{id:true}});await this.audit(tx,"clinic.create","Clinic",row.id);return {ok:true,data:row} as const;}); } catch{return unavailable();} }
  async update(id:string,input:unknown){const denied=this.denied();if(denied)return denied;const p=clinicSchema.safeParse(input);if(!p.success)return validation(p.error);try{return await this.prisma.$transaction(async tx=>{const exists=await tx.clinic.findFirst({where:{id,tenantId:this.context.tenantId},select:{id:true}});if(!exists)return actionFailure("NOT_FOUND","Unidade não encontrada.");await tx.clinic.update({where:{id},data:{name:p.data.name,slug:p.data.slug,timezoneOverride:p.data.timezoneOverride,status:p.data.active?"ACTIVE":"INACTIVE"}});await this.audit(tx,"clinic.update","Clinic",id);return {ok:true,data:{id}} as const;});}catch{return unavailable();}}
}

const professionalSchema=z.object({name:label,specialty:label,registrationNumber:z.string().trim().max(40).nullable().default(null),registrationRegion:z.string().trim().max(20).nullable().default(null),color:z.string().regex(/^#[0-9a-fA-F]{6}$/).nullable().default(null),active:z.boolean().default(true),clinicIds:z.array(uuid).min(1)});
export class ProfessionalService extends TenantService { async create(input:unknown){const denied=this.denied();if(denied)return denied;const p=professionalSchema.safeParse(input);if(!p.success)return validation(p.error);try{return await this.prisma.$transaction(async tx=>{const count=await tx.clinic.count({where:{tenantId:this.context.tenantId,id:{in:p.data.clinicIds}}});if(count!==new Set(p.data.clinicIds).size)return actionFailure("NOT_FOUND","Uma unidade não foi encontrada.");const row=await tx.professional.create({data:{tenantId:this.context.tenantId,name:p.data.name,specialty:p.data.specialty,registrationNumber:p.data.registrationNumber,registrationRegion:p.data.registrationRegion,color:p.data.color,status:p.data.active?"ACTIVE":"INACTIVE",clinics:{create:p.data.clinicIds.map(clinicId=>({tenantId:this.context.tenantId,clinicId}))}},select:{id:true}});await this.audit(tx,"professional.create","Professional",row.id);return {ok:true,data:row} as const;});}catch{return unavailable();}} async update(id:string,input:unknown){const denied=this.denied();if(denied)return denied;const p=professionalSchema.safeParse(input);if(!p.success)return validation(p.error);try{return await this.prisma.$transaction(async tx=>{const row=await tx.professional.findFirst({where:{id,tenantId:this.context.tenantId},select:{id:true}});if(!row)return actionFailure("NOT_FOUND","Profissional não encontrado.");const count=await tx.clinic.count({where:{tenantId:this.context.tenantId,id:{in:p.data.clinicIds}}});if(count!==new Set(p.data.clinicIds).size)return actionFailure("NOT_FOUND","Uma unidade não foi encontrada.");await tx.professional.update({where:{id},data:{name:p.data.name,specialty:p.data.specialty,registrationNumber:p.data.registrationNumber,registrationRegion:p.data.registrationRegion,color:p.data.color,status:p.data.active?"ACTIVE":"INACTIVE"}});await tx.professionalClinic.deleteMany({where:{tenantId:this.context.tenantId,professionalId:id,clinicId:{notIn:p.data.clinicIds}}});for(const clinicId of p.data.clinicIds)await tx.professionalClinic.upsert({where:{professionalId_clinicId:{professionalId:id,clinicId}},create:{tenantId:this.context.tenantId,professionalId:id,clinicId},update:{active:true}});await this.audit(tx,"professional.update","Professional",id);return {ok:true,data:{id}} as const;});}catch{return unavailable();}} }

const procedureSchema=z.object({name:label,category:z.string().trim().max(80).nullable().default(null),durationMinutes:z.number().int().min(5).max(1440),priceCents:z.number().int().nonnegative(),active:z.boolean().default(true)});
export class ProcedureService extends TenantService { async create(input:unknown){return this.save(undefined,input)} async update(id:string,input:unknown){return this.save(id,input)} private async save(id:string|undefined,input:unknown){const denied=this.denied();if(denied)return denied;const p=procedureSchema.safeParse(input);if(!p.success)return validation(p.error);try{return await this.prisma.$transaction(async tx=>{if(id&&!await tx.procedure.findFirst({where:{id,tenantId:this.context.tenantId},select:{id:true}}))return actionFailure("NOT_FOUND","Procedimento não encontrado.");const data={tenantId:this.context.tenantId,name:p.data.name,category:p.data.category,durationMinutes:p.data.durationMinutes,defaultPriceCents:p.data.priceCents,active:p.data.active};const row=id?await tx.procedure.update({where:{id},data,select:{id:true}}):await tx.procedure.create({data,select:{id:true}});await this.audit(tx,id?"procedure.update":"procedure.create","Procedure",row.id);return {ok:true,data:row} as const;});}catch{return unavailable();}} }

const resourceSchema=z.object({clinicId:uuid,name:label,type:z.enum(["CHAIR","ROOM","EQUIPMENT","OTHER"]),active:z.boolean().default(true)});
export class ResourceService extends TenantService { async create(input:unknown){return this.save(undefined,input)} async update(id:string,input:unknown){return this.save(id,input)} private async save(id:string|undefined,input:unknown){const denied=this.denied();if(denied)return denied;const p=resourceSchema.safeParse(input);if(!p.success)return validation(p.error);try{return await this.prisma.$transaction(async tx=>{if(!await tx.clinic.findFirst({where:{id:p.data.clinicId,tenantId:this.context.tenantId},select:{id:true}}))return actionFailure("NOT_FOUND","Unidade não encontrada.");if(id&&!await tx.resource.findFirst({where:{id,tenantId:this.context.tenantId},select:{id:true}}))return actionFailure("NOT_FOUND","Recurso não encontrado.");const data={tenantId:this.context.tenantId,...p.data};const row=id?await tx.resource.update({where:{id},data,select:{id:true}}):await tx.resource.create({data,select:{id:true}});await this.audit(tx,id?"resource.update":"resource.create","Resource",row.id);return {ok:true,data:row} as const;});}catch{return unavailable();}} }

const hoursSchema=z.object({professionalId:uuid,clinicId:uuid,slots:z.array(z.object({weekday:z.number().int().min(0).max(6),startMinute:z.number().int().min(0).max(1439),endMinute:z.number().int().min(1).max(1440),active:z.boolean().default(true)}).refine(x=>x.endMinute>x.startMinute,"O fim deve ser posterior ao início."))});
export class WorkingHoursService extends TenantService {async replace(input:unknown){const denied=this.denied();if(denied)return denied;const p=hoursSchema.safeParse(input);if(!p.success)return validation(p.error);try{return await this.prisma.$transaction(async tx=>{if(!await tx.professionalClinic.findFirst({where:{tenantId:this.context.tenantId,professionalId:p.data.professionalId,clinicId:p.data.clinicId,active:true},select:{professionalId:true}}))return actionFailure("NOT_FOUND","Vínculo entre profissional e unidade não encontrado.");await tx.workingHours.deleteMany({where:{tenantId:this.context.tenantId,professionalId:p.data.professionalId,clinicId:p.data.clinicId}});if(p.data.slots.length)await tx.workingHours.createMany({data:p.data.slots.map(slot=>({tenantId:this.context.tenantId,professionalId:p.data.professionalId,clinicId:p.data.clinicId,...slot}))});await this.audit(tx,"working-hours.replace","Professional",p.data.professionalId);return {ok:true,data:{count:p.data.slots.length}} as const;});}catch{return unavailable();}}}

const blockSchema=z.object({clinicId:uuid.nullable().default(null),professionalId:uuid.nullable().default(null),resourceId:uuid.nullable().default(null),startsAt:z.coerce.date(),endsAt:z.coerce.date(),reason:z.string().trim().max(240).nullable().default(null)}).refine(x=>x.clinicId||x.professionalId||x.resourceId,{message:"Selecione o escopo do bloqueio."}).refine(x=>x.endsAt>x.startsAt,{message:"O fim deve ser posterior ao início."});
export class ScheduleBlockService extends TenantService {async create(input:unknown){const denied=this.denied();if(denied)return denied;const p=blockSchema.safeParse(input);if(!p.success)return validation(p.error);try{return await this.prisma.$transaction(async tx=>{for(const [model,id] of [["clinic",p.data.clinicId],["professional",p.data.professionalId],["resource",p.data.resourceId]] as const)if(id&&!await (tx[model] as typeof tx.clinic).findFirst({where:{id,tenantId:this.context.tenantId},select:{id:true}}))return actionFailure("NOT_FOUND","Escopo do bloqueio não encontrado.");const row=await tx.scheduleBlock.create({data:{tenantId:this.context.tenantId,createdByMembershipId:this.context.membershipId,...p.data},select:{id:true}});await this.audit(tx,"schedule-block.create","ScheduleBlock",row.id);return {ok:true,data:row} as const;});}catch{return unavailable();}}async remove(id:string){const denied=this.denied();if(denied)return denied;try{return await this.prisma.$transaction(async tx=>{if(!await tx.scheduleBlock.findFirst({where:{id,tenantId:this.context.tenantId},select:{id:true}}))return actionFailure("NOT_FOUND","Bloqueio não encontrado.");await tx.scheduleBlock.delete({where:{id}});await this.audit(tx,"schedule-block.delete","ScheduleBlock",id);return {ok:true,data:{id}} as const;});}catch{return unavailable();}}}

const patientSchema=z.object({name:label,phoneE164:z.string().regex(/^\+[1-9]\d{7,14}$/).nullable().default(null),emailNormalized:z.string().trim().email().toLowerCase().nullable().default(null)});
export class QuickPatientService extends TenantService {async create(input:unknown){const denied=this.denied();if(denied)return denied;const p=patientSchema.safeParse(input);if(!p.success)return validation(p.error);try{return await this.prisma.$transaction(async tx=>{if(p.data.phoneE164){const found=await tx.patient.findFirst({where:{tenantId:this.context.tenantId,phoneE164:p.data.phoneE164,archivedAt:null},select:{id:true,name:true}});if(found)return {ok:true,data:found} as const;}const row=await tx.patient.create({data:{tenantId:this.context.tenantId,...p.data},select:{id:true,name:true}});await this.audit(tx,"patient.quick-create","Patient",row.id);return {ok:true,data:row} as const;});}catch{return unavailable();}}}

const appointmentSchema=z.object({clinicId:uuid,patientId:uuid,professionalId:uuid,procedureId:uuid.nullable().default(null),resourceId:uuid.nullable().default(null),startsAt:z.coerce.date(),endsAt:z.coerce.date(),priceCents:z.number().int().nonnegative().default(0),source:z.string().trim().max(80).nullable().default(null)}).refine(x=>x.endsAt>x.startsAt,{message:"O fim deve ser posterior ao início."});
const dbStatus=(status:AppointmentStatus)=>status.toUpperCase() as DbAppointmentStatus;
const inactiveStatuses: DbAppointmentStatus[]=["CANCELLED","NO_SHOW","RESCHEDULED"];
export class AppointmentService extends TenantService {
  private async references(tx:Tx,p:z.infer<typeof appointmentSchema>){const [pc,patient,procedure,resource]=await Promise.all([tx.professionalClinic.findFirst({where:{tenantId:this.context.tenantId,clinicId:p.clinicId,professionalId:p.professionalId,active:true},select:{professionalId:true}}),tx.patient.findFirst({where:{id:p.patientId,tenantId:this.context.tenantId,archivedAt:null},select:{id:true}}),p.procedureId?tx.procedure.findFirst({where:{id:p.procedureId,tenantId:this.context.tenantId,active:true},select:{id:true}}):true,p.resourceId?tx.resource.findFirst({where:{id:p.resourceId,tenantId:this.context.tenantId,clinicId:p.clinicId,active:true},select:{id:true}}):true]);return !!(pc&&patient&&procedure&&resource)}
  private async conflict(tx:Tx,p:z.infer<typeof appointmentSchema>,excludeId?:string){const overlap={tenantId:this.context.tenantId,...(excludeId?{id:{not:excludeId}}:{}),status:{notIn:inactiveStatuses},startsAt:{lt:p.endsAt},endsAt:{gt:p.startsAt}};const [appointment,block]=await Promise.all([tx.appointment.findFirst({where:{...overlap,OR:[{professionalId:p.professionalId},...(p.resourceId?[{resourceId:p.resourceId}]:[])]},select:{id:true}}),tx.scheduleBlock.findFirst({where:{tenantId:this.context.tenantId,startsAt:{lt:p.endsAt},endsAt:{gt:p.startsAt},OR:[{clinicId:p.clinicId},{professionalId:p.professionalId},...(p.resourceId?[{resourceId:p.resourceId}]:[])]},select:{id:true}})]);return !!(appointment||block)}
  async create(input:unknown){const denied=this.denied();if(denied)return denied;const p=appointmentSchema.safeParse(input);if(!p.success)return validation(p.error);try{return await this.prisma.$transaction(async tx=>{if(!await this.references(tx,p.data))return actionFailure("NOT_FOUND","Dados relacionados ao agendamento não foram encontrados.");if(await this.conflict(tx,p.data))return actionFailure("CONFLICT","O profissional ou recurso não está disponível neste horário.");const row=await tx.appointment.create({data:{tenantId:this.context.tenantId,createdByMembershipId:this.context.membershipId,...p.data},select:{id:true}});await tx.appointmentStatusHistory.create({data:{tenantId:this.context.tenantId,appointmentId:row.id,toStatus:"SCHEDULED",changedByMembershipId:this.context.membershipId}});await this.audit(tx,"appointment.create","Appointment",row.id);return {ok:true,data:row} as const;},{isolationLevel:"Serializable"});}catch{return unavailable();}}
  async reschedule(id:string,input:unknown){const denied=this.denied();if(denied)return denied;const times=z.object({startsAt:z.coerce.date(),endsAt:z.coerce.date()}).refine(x=>x.endsAt>x.startsAt).safeParse(input);if(!times.success)return validation(times.error);try{return await this.prisma.$transaction(async tx=>{const old=await tx.appointment.findFirst({where:{id,tenantId:this.context.tenantId},select:{clinicId:true,patientId:true,professionalId:true,procedureId:true,resourceId:true,priceCents:true,source:true,status:true}});if(!old)return actionFailure("NOT_FOUND","Agendamento não encontrado.");const next={...old,...times.data};if(await this.conflict(tx,next,id))return actionFailure("CONFLICT","O profissional ou recurso não está disponível neste horário.");await tx.appointment.update({where:{id},data:{...times.data,status:"RESCHEDULED"}});const row=await tx.appointment.create({data:{tenantId:this.context.tenantId,createdByMembershipId:this.context.membershipId,...next,status:"SCHEDULED"},select:{id:true}});await tx.appointmentStatusHistory.createMany({data:[{tenantId:this.context.tenantId,appointmentId:id,fromStatus:old.status,toStatus:"RESCHEDULED",changedByMembershipId:this.context.membershipId},{tenantId:this.context.tenantId,appointmentId:row.id,toStatus:"SCHEDULED",changedByMembershipId:this.context.membershipId,reason:`Reagendado de ${id}`}]});await this.audit(tx,"appointment.reschedule","Appointment",row.id);return {ok:true,data:row} as const;},{isolationLevel:"Serializable"});}catch{return unavailable();}}
  async transition(id:string,status:AppointmentStatus,reason?:string){const denied=this.denied();if(denied)return denied;const allowed:Record<AppointmentStatus,AppointmentStatus[]>={scheduled:["confirmed","cancelled"],confirmed:["arrived","no_show","cancelled"],arrived:["attended","cancelled"],attended:[],no_show:[],cancelled:[],rescheduled:[]};try{return await this.prisma.$transaction(async tx=>{const row=await tx.appointment.findFirst({where:{id,tenantId:this.context.tenantId},select:{status:true}});if(!row)return actionFailure("NOT_FOUND","Agendamento não encontrado.");const from=mapAppointmentStatus(row.status);if(!allowed[from].includes(status))return actionFailure("CONFLICT","Esta mudança de status não é permitida.");await tx.appointment.update({where:{id},data:{status:dbStatus(status),...(status==="cancelled"?{cancellationReason:reason ?? null}: {})}});await tx.appointmentStatusHistory.create({data:{tenantId:this.context.tenantId,appointmentId:id,fromStatus:row.status,toStatus:dbStatus(status),changedByMembershipId:this.context.membershipId,reason:reason ?? null}});await this.audit(tx,`appointment.${status}`,"Appointment",id);return {ok:true,data:{id,status}} as const;});}catch{return unavailable();}}
  async history(id:string){try{if(!await this.prisma.appointment.findFirst({where:{id,tenantId:this.context.tenantId},select:{id:true}}))return actionFailure("NOT_FOUND","Agendamento não encontrado.");const rows=await this.prisma.appointmentStatusHistory.findMany({where:{tenantId:this.context.tenantId,appointmentId:id},select:{fromStatus:true,toStatus:true,changedAt:true,reason:true},orderBy:[{changedAt:"desc"},{id:"desc"}]});return {ok:true,data:rows.map(r=>({fromStatus:r.fromStatus?mapAppointmentStatus(r.fromStatus):null,toStatus:mapAppointmentStatus(r.toStatus),changedAt:r.changedAt.toISOString(),reason:r.reason}))} as const;}catch{return unavailable();}}
}
