import "server-only";
import {createHash,randomBytes} from "node:crypto";
import {z} from "zod";
import type {PrismaClient} from "@/generated/prisma/client";
import type {ApplicationContext} from "@/domains/application/context";
import {hasPermission} from "@/domains/application/rbac";
import {actionFailure,type ActionResult} from "@/domains/application/actions";
import type {PublicTreatmentPlanView} from "@/domains/application/view-models";
import {calculateTreatmentPlanTotals} from "@/domains/application/treatment-plan";
import {getPrismaClient} from "@/lib/db";import {encryptField} from "@/lib/security/field-encryption";import {createCorrelationId,redactPreview} from "@/domains/application/integrations";import {appUrl} from "@/lib/config/public-urls";import {PilotSyntheticDataError,validateSyntheticClinicalInput} from "@/domains/pilot/data-policy";
type Tx=Omit<PrismaClient,"$connect"|"$disconnect"|"$on"|"$transaction"|"$extends">;const uuid=z.string().uuid();
const fail=(e:z.ZodError):ActionResult<never>=>actionFailure("VALIDATION_ERROR","Revise os campos informados.",e.flatten().fieldErrors as Record<string,string[]>);
const pilotGuard=(input:Record<string,unknown>)=>{try{validateSyntheticClinicalInput(input);return null}catch(error){if(error instanceof PilotSyntheticDataError)return actionFailure("VALIDATION_ERROR","PILOT_SYNTHETIC_DATA_REQUIRED");throw error}};
abstract class Base{constructor(protected c:ApplicationContext,protected p:PrismaClient=getPrismaClient()){}denied(){return hasPermission(this.c.membershipRole,"treatment_plans.manage")||hasPermission(this.c.membershipRole,"inbox.manage")?null:actionFailure("ACCESS_DENIED","Você não tem permissão para esta ação.")}audit(tx:Tx,a:string,t:string,id:string){return tx.auditLog.create({data:{tenantId:this.c.tenantId,actorUserId:this.c.userId,actorMembershipId:this.c.membershipId,action:a,resourceType:t,resourceId:id,outcome:"SUCCESS"},select:{id:true}})}unavailable(){return actionFailure("UNAVAILABLE","Não foi possível concluir a operação. Tente novamente.")}}
const item=z.object({procedureId:uuid.nullable().default(null),description:z.string().trim().min(2).max(240),quantity:z.number().int().min(1).max(100),unitPriceCents:z.number().int().nonnegative().max(100_000_000),discountCents:z.number().int().nonnegative().default(0)});
const planInput=z.object({patientId:uuid,clinicId:uuid.nullable().default(null),professionalId:uuid.nullable().default(null),leadId:uuid.nullable().default(null),title:z.string().trim().min(2).max(160),discountCents:z.number().int().nonnegative().default(0),expiresAt:z.coerce.date().nullable().default(null),items:z.array(item).min(1).max(50)});
function totals(data:z.infer<typeof planInput>){const calculated=calculateTreatmentPlanTotals(data.items,data.discountCents);const items=data.items.map((x,i)=>({...x,totalCents:calculated.itemTotals[i]!,position:i}));return {items,subtotalCents:calculated.subtotalCents,totalCents:calculated.totalCents}}
export class TreatmentPlanService extends Base{
 private async owned(tx:Tx,id:string){return tx.treatmentPlan.findFirst({where:{id,tenantId:this.c.tenantId,...(this.c.membershipRole==="PROFESSIONAL"?{professional:{membershipId:this.c.membershipId}}:{})},select:{id:true,status:true,professionalId:true}})}
 private async refs(tx:Tx,d:z.infer<typeof planInput>){const [patient,clinic,lead,professional,procedures]=await Promise.all([tx.patient.findFirst({where:{id:d.patientId,tenantId:this.c.tenantId,archivedAt:null},select:{id:true}}),d.clinicId?tx.clinic.findFirst({where:{id:d.clinicId,tenantId:this.c.tenantId},select:{id:true}}):true,d.leadId?tx.lead.findFirst({where:{id:d.leadId,tenantId:this.c.tenantId},select:{id:true,patientId:true}}):true,d.professionalId?tx.professional.findFirst({where:{id:d.professionalId,tenantId:this.c.tenantId,...(this.c.membershipRole==="PROFESSIONAL"?{membershipId:this.c.membershipId}:{})},select:{id:true}}):this.c.membershipRole!=="PROFESSIONAL",tx.procedure.count({where:{tenantId:this.c.tenantId,id:{in:d.items.flatMap(x=>x.procedureId?[x.procedureId]:[])}}})]);return Boolean(patient&&clinic&&lead&&professional&&procedures===new Set(d.items.flatMap(x=>x.procedureId?[x.procedureId]:[])).size&&(!d.leadId||(lead!==true&&(!lead.patientId||lead.patientId===d.patientId))))}
 async create(input:unknown){const d=this.denied();if(d)return d;const v=planInput.safeParse(input);if(!v.success)return fail(v.error);const guarded=pilotGuard({...v.data,description:v.data.items.map(x=>x.description).join(" ")});if(guarded)return guarded;try{const calc=totals(v.data);return await this.p.$transaction(async tx=>{if(!await this.refs(tx,v.data))return actionFailure("NOT_FOUND","Paciente ou relação do orçamento não encontrada.");const row=await tx.treatmentPlan.create({data:{tenantId:this.c.tenantId,patientId:v.data.patientId,clinicId:v.data.clinicId,professionalId:v.data.professionalId,leadId:v.data.leadId,title:v.data.title,discountCents:v.data.discountCents,subtotalCents:calc.subtotalCents,totalCents:calc.totalCents,expiresAt:v.data.expiresAt,createdByMembershipId:this.c.membershipId,items:{create:calc.items.map(x=>({tenantId:this.c.tenantId,...x}))},statusHistory:{create:{tenantId:this.c.tenantId,toStatus:"DRAFT",changedByMembershipId:this.c.membershipId,reason:"Orçamento criado"}}},select:{id:true}});await this.audit(tx,"treatment-plan.create","TreatmentPlan",row.id);return {ok:true,data:row} as const})}catch{return actionFailure("VALIDATION_ERROR","Os valores do orçamento são inválidos.")}}
 async update(id:string,input:unknown){const d=this.denied();if(d)return d;const v=planInput.safeParse(input);if(!v.success)return fail(v.error);const guarded=pilotGuard({...v.data,description:v.data.items.map(x=>x.description).join(" ")});if(guarded)return guarded;try{const calc=totals(v.data);return await this.p.$transaction(async tx=>{const old=await this.owned(tx,id);if(!old)return actionFailure("NOT_FOUND","Orçamento não encontrado.");if(old.status!=="DRAFT")return actionFailure("CONFLICT","Somente rascunhos podem ser editados.");if(!await this.refs(tx,v.data))return actionFailure("NOT_FOUND","Paciente ou relação não encontrada.");await tx.treatmentPlanItem.deleteMany({where:{treatmentPlanId:id,tenantId:this.c.tenantId}});await tx.treatmentPlan.update({where:{id},data:{patientId:v.data.patientId,clinicId:v.data.clinicId,professionalId:v.data.professionalId,leadId:v.data.leadId,title:v.data.title,discountCents:v.data.discountCents,subtotalCents:calc.subtotalCents,totalCents:calc.totalCents,expiresAt:v.data.expiresAt,items:{create:calc.items.map(x=>({tenantId:this.c.tenantId,...x}))}}});await this.audit(tx,"treatment-plan.update","TreatmentPlan",id);return {ok:true,data:{id}} as const})}catch{return this.unavailable()}}
 async duplicate(id:string){const d=this.denied();if(d)return d;try{return await this.p.$transaction(async tx=>{const old=await tx.treatmentPlan.findFirst({where:{id,tenantId:this.c.tenantId,...(this.c.membershipRole==="PROFESSIONAL"?{professional:{membershipId:this.c.membershipId}}:{})},select:{patientId:true,clinicId:true,professionalId:true,leadId:true,title:true,subtotalCents:true,discountCents:true,totalCents:true,expiresAt:true,items:{where:{tenantId:this.c.tenantId},select:{procedureId:true,description:true,quantity:true,unitPriceCents:true,discountCents:true,totalCents:true,position:true}}}});if(!old)return actionFailure("NOT_FOUND","Orçamento não encontrado.");const row=await tx.treatmentPlan.create({data:{tenantId:this.c.tenantId,...old,title:`Cópia de ${old.title}`.slice(0,160),createdByMembershipId:this.c.membershipId,status:"DRAFT",items:{create:old.items.map(x=>({tenantId:this.c.tenantId,...x}))},statusHistory:{create:{tenantId:this.c.tenantId,toStatus:"DRAFT",changedByMembershipId:this.c.membershipId,reason:"Orçamento duplicado"}}},select:{id:true}});await this.audit(tx,"treatment-plan.duplicate","TreatmentPlan",row.id);return {ok:true,data:row} as const})}catch{return this.unavailable()}}
 async transition(id:string,input:unknown){const d=this.denied();if(d)return d;const v=z.object({status:z.enum(["SENT","ACCEPTED","REJECTED","EXPIRED","CANCELLED"]),reason:z.string().trim().max(240).nullable().default(null)}).safeParse(input);if(!v.success)return fail(v.error);const guarded=pilotGuard(v.data);if(guarded)return guarded;try{return await this.p.$transaction(async tx=>{const old=await this.owned(tx,id);if(!old)return actionFailure("NOT_FOUND","Orçamento não encontrado.");const allowed:Record<string,string[]>={DRAFT:["SENT","CANCELLED"],SENT:["ACCEPTED","REJECTED","EXPIRED","CANCELLED"],VIEWED:["ACCEPTED","REJECTED","EXPIRED","CANCELLED"]};if(!allowed[old.status]?.includes(v.data.status))return actionFailure("CONFLICT","Transição de status inválida.");const now=new Date();await tx.treatmentPlan.update({where:{id},data:{status:v.data.status,...(v.data.status==="SENT"?{sentAt:now}:{}),...(v.data.status==="ACCEPTED"?{acceptedAt:now}:{}),...(v.data.status==="REJECTED"?{rejectedAt:now}:{})}});await tx.treatmentPlanStatusHistory.create({data:{tenantId:this.c.tenantId,treatmentPlanId:id,fromStatus:old.status,toStatus:v.data.status,changedByMembershipId:this.c.membershipId,reason:v.data.reason}});await this.audit(tx,"treatment-plan.status-change","TreatmentPlan",id);return {ok:true,data:{id,status:v.data.status.toLowerCase()}} as const})}catch{return this.unavailable()}}
 async createPublicLink(id:string){const d=this.denied();if(d)return d;const token=randomBytes(32).toString("base64url"),hash=createHash("sha256").update(token).digest("hex"),expiresAt=new Date(Date.now()+30*864e5);try{return await this.p.$transaction(async tx=>{const old=await this.owned(tx,id);if(!old)return actionFailure("NOT_FOUND","Orçamento não encontrado.");await tx.treatmentPlan.update({where:{id},data:{publicTokenHash:hash,publicTokenExpiresAt:expiresAt}});await this.audit(tx,"treatment-plan.public-link","TreatmentPlan",id);return {ok:true,data:{url:`${appUrl}/plano#token=${encodeURIComponent(token)}`,expiresAt:expiresAt.toISOString()}} as const})}catch{return this.unavailable()}}
}
const conversationInput=z.object({channel:z.enum(["INTERNAL","WHATSAPP","INSTAGRAM","MESSENGER","EMAIL"]),patientId:uuid.nullable().default(null),leadId:uuid.nullable().default(null),integrationId:uuid.nullable().default(null)}).refine(x=>x.patientId||x.leadId,{message:"Vincule um paciente ou lead."});
export class ConversationService extends Base{
 private owned(tx:Tx,id:string){return tx.conversation.findFirst({where:{id,tenantId:this.c.tenantId,...(this.c.membershipRole==="PROFESSIONAL"?{patient:{appointments:{some:{tenantId:this.c.tenantId,professionalClinic:{professional:{membershipId:this.c.membershipId}}}}}}:{})},select:{id:true,channel:true,integrationId:true}})}
 async create(input:unknown){const d=this.denied();if(d)return d;const v=conversationInput.safeParse(input);if(!v.success)return fail(v.error);try{return await this.p.$transaction(async tx=>{if(this.c.membershipRole==="PROFESSIONAL")return actionFailure("ACCESS_DENIED","Profissionais não podem criar conversas neste momento.");const [patient,lead,integration]=await Promise.all([v.data.patientId?tx.patient.findFirst({where:{id:v.data.patientId,tenantId:this.c.tenantId},select:{id:true}}):true,v.data.leadId?tx.lead.findFirst({where:{id:v.data.leadId,tenantId:this.c.tenantId},select:{id:true}}):true,v.data.integrationId?tx.integration.findFirst({where:{id:v.data.integrationId,tenantId:this.c.tenantId,status:"CONNECTED"},select:{id:true}}):true]);if(!patient||!lead||!integration)return actionFailure("NOT_FOUND","Contato ou integração não encontrado.");if(v.data.channel!=="INTERNAL"&&!v.data.integrationId)return actionFailure("CONFLICT","Uma integração conectada é obrigatória para canal externo.");const row=await tx.conversation.create({data:{tenantId:this.c.tenantId,...v.data},select:{id:true}});await this.audit(tx,"conversation.create","Conversation",row.id);return {ok:true,data:row} as const})}catch{return this.unavailable()}}
 async link(id:string,input:unknown){const d=this.denied();if(d)return d;const v=z.object({patientId:uuid.nullable(),leadId:uuid.nullable()}).refine(x=>x.patientId||x.leadId).safeParse(input);if(!v.success)return fail(v.error);try{return await this.p.$transaction(async tx=>{if(!await this.owned(tx,id))return actionFailure("NOT_FOUND","Conversa não encontrada.");const [patient,lead]=await Promise.all([v.data.patientId?tx.patient.findFirst({where:{id:v.data.patientId,tenantId:this.c.tenantId},select:{id:true}}):true,v.data.leadId?tx.lead.findFirst({where:{id:v.data.leadId,tenantId:this.c.tenantId},select:{id:true}}):true]);if(!patient||!lead)return actionFailure("NOT_FOUND","Contato não encontrado.");await tx.conversation.update({where:{id},data:v.data});await this.audit(tx,"conversation.link","Conversation",id);return {ok:true,data:{id}} as const})}catch{return this.unavailable()}}
 async transition(id:string,input:unknown){const d=this.denied();if(d)return d;const v=z.object({status:z.enum(["OPEN","PENDING","CLOSED","ARCHIVED"])}).safeParse(input);if(!v.success)return fail(v.error);try{return await this.p.$transaction(async tx=>{if(!await this.owned(tx,id))return actionFailure("NOT_FOUND","Conversa não encontrada.");await tx.conversation.update({where:{id},data:{status:v.data.status}});await this.audit(tx,"conversation.status-change","Conversation",id);return {ok:true,data:{id,status:v.data.status.toLowerCase()}} as const})}catch{return this.unavailable()}}
 async addMessage(id:string,input:unknown){const d=this.denied();if(d)return d;const v=z.object({preview:z.string().trim().min(1).max(160),internal:z.boolean().default(false)}).safeParse(input);if(!v.success)return fail(v.error);const guarded=pilotGuard(v.data);if(guarded)return guarded;try{return await this.p.$transaction(async tx=>{const c=await this.owned(tx,id);if(!c)return actionFailure("NOT_FOUND","Conversa não encontrada.");if(this.c.membershipRole==="PROFESSIONAL"&&!v.data.internal)return actionFailure("ACCESS_DENIED","Profissionais só podem registrar nota interna.");if(!v.data.internal){if(c.channel==="INTERNAL"||!c.integrationId)return actionFailure("CONFLICT","Canal externo sem integração conectada.");if(!await tx.integration.findFirst({where:{id:c.integrationId,tenantId:this.c.tenantId,status:"CONNECTED"},select:{id:true}}))return actionFailure("CONFLICT","A integração não está conectada.")}const now=new Date(),row=await tx.message.create({data:{tenantId:this.c.tenantId,conversationId:id,direction:v.data.internal?"INTERNAL":"OUTBOUND",status:v.data.internal?"SENT":"PENDING",contentType:v.data.internal?"internal_note":"text",bodyCiphertext:encryptField(v.data.preview),bodyPreviewRedacted:redactPreview(v.data.preview),correlationId:createCorrelationId(),sentAt:v.data.internal?now:null},select:{id:true,status:true}});await tx.conversation.update({where:{id},data:{lastMessageAt:now}});await this.audit(tx,v.data.internal?"message.internal-note":"message.enqueue","Message",row.id);return {ok:true,data:{id:row.id,status:row.status.toLowerCase()}} as const})}catch{return this.unavailable()}}
 async markRead(id:string){const d=this.denied();if(d)return d;try{return await this.p.$transaction(async tx=>{if(!await this.owned(tx,id))return actionFailure("NOT_FOUND","Conversa não encontrada.");const result=await tx.message.updateMany({where:{tenantId:this.c.tenantId,conversationId:id,direction:"INBOUND",readAt:null},data:{readAt:new Date(),status:"READ"}});await this.audit(tx,"conversation.mark-read","Conversation",id);return {ok:true,data:{id,count:result.count}} as const})}catch{return this.unavailable()}}
}
export class PublicTreatmentPlanService{constructor(private p:PrismaClient=getPrismaClient()){}private hash(token:string){return createHash("sha256").update(token).digest("hex")}async view(token:string):Promise<PublicTreatmentPlanView|null>{if(token.length<32)return null;const now=new Date(),row=await this.p.treatmentPlan.findFirst({where:{publicTokenHash:this.hash(token),publicTokenExpiresAt:{gt:now},status:{in:["SENT","VIEWED"]}},select:{id:true,tenantId:true,title:true,status:true,subtotalCents:true,discountCents:true,totalCents:true,expiresAt:true,patient:{select:{name:true}},clinic:{select:{name:true}},items:{select:{id:true,procedureId:true,description:true,quantity:true,unitPriceCents:true,discountCents:true,totalCents:true,position:true,procedure:{select:{name:true}}},orderBy:[{position:"asc"},{id:"asc"}]}}});if(!row)return null;if(row.status==="SENT")await this.p.$transaction([this.p.treatmentPlan.update({where:{id:row.id},data:{status:"VIEWED"}}),this.p.treatmentPlanStatusHistory.create({data:{tenantId:row.tenantId,treatmentPlanId:row.id,fromStatus:"SENT",toStatus:"VIEWED",reason:"Link público visualizado"}})]);return {title:row.title,status:(row.status==="SENT"?"viewed":row.status.toLowerCase()) as never,patientFirstName:row.patient.name.split(/\s+/)[0]??"Paciente",clinicName:row.clinic?.name??null,items:row.items.map(x=>({...x,procedureName:x.procedure?.name??null})),subtotalCents:row.subtotalCents,discountCents:row.discountCents,totalCents:row.totalCents,expiresAt:row.expiresAt?.toISOString()??null}}async respond(token:string,response:"ACCEPTED"|"REJECTED"){const hash=this.hash(token),now=new Date();return this.p.$transaction(async tx=>{const row=await tx.treatmentPlan.findFirst({where:{publicTokenHash:hash,publicTokenExpiresAt:{gt:now},status:{in:["SENT","VIEWED"]}},select:{id:true,tenantId:true,status:true}});if(!row)return false;await tx.treatmentPlan.update({where:{id:row.id},data:{status:response,acceptedAt:response==="ACCEPTED"?now:null,rejectedAt:response==="REJECTED"?now:null}});await tx.treatmentPlanStatusHistory.create({data:{tenantId:row.tenantId,treatmentPlanId:row.id,fromStatus:row.status,toStatus:response,reason:"Resposta pelo link público"}});return true})}}
