import "server-only";
import type {Prisma,PrismaClient} from "@/generated/prisma/client";
import type {ApplicationContext} from "@/domains/application/context";
import type {ConversationReader,TreatmentPlanReader} from "@/domains/application/readers";
import {normalizePage,parseDateRange} from "@/domains/application/query";
import {getPrismaClient} from "@/lib/db";
const iso=(d:Date|null)=>d?.toISOString()??null;const lower=(s:string)=>s.toLowerCase() as never;
const paged=<T>(items:T[],total:number,offset:number,limit:number)=>({items,page:{offset,limit,total,hasMore:offset+items.length<total}});
const professionalScope=(c:ApplicationContext)=>c.membershipRole==="PROFESSIONAL"?{professional:{membershipId:c.membershipId}}:{};
const planSelect={id:true,title:true,status:true,patientId:true,professionalId:true,clinicId:true,leadId:true,subtotalCents:true,discountCents:true,totalCents:true,expiresAt:true,sentAt:true,acceptedAt:true,rejectedAt:true,createdAt:true,updatedAt:true,patient:{select:{name:true}},professional:{select:{name:true}},clinic:{select:{name:true}}} as const;
type PlanRow=Prisma.TreatmentPlanGetPayload<{select:typeof planSelect}>;
function plan(row:PlanRow){return {id:row.id,title:row.title,status:lower(row.status),patientId:row.patientId,patientName:row.patient.name,professionalId:row.professionalId,professionalName:row.professional?.name??null,clinicId:row.clinicId,clinicName:row.clinic?.name??null,leadId:row.leadId,subtotalCents:row.subtotalCents,discountCents:row.discountCents,totalCents:row.totalCents,expiresAt:iso(row.expiresAt),updatedAt:row.updatedAt.toISOString()}}
export class PrismaTreatmentPlanReader implements TreatmentPlanReader{
 constructor(private context:ApplicationContext,private prisma:PrismaClient=getPrismaClient()){}
 async list(q:Parameters<TreatmentPlanReader["list"]>[0]={}){const {offset,limit}=normalizePage({...q,limit:q.limit??25});const range=q.range?parseDateRange(q.range):null;const where={tenantId:this.context.tenantId,...professionalScope(this.context),...(q.search?{OR:[{title:{contains:q.search,mode:"insensitive" as const}},{patient:{name:{contains:q.search,mode:"insensitive" as const}}}]}:{}),...(q.status?{status:q.status.toUpperCase() as never}:{}),...(q.patientId?{patientId:q.patientId}:{}),...(q.professionalId?{professionalId:q.professionalId}:{}),...(q.clinicId?{clinicId:q.clinicId}:{}),...(q.leadId?{leadId:q.leadId}:{}),...(range?{createdAt:{gte:range.from,lt:range.to}}:{}),...(q.expiringSoon?{expiresAt:{gte:new Date(),lte:new Date(Date.now()+7*864e5)}}:{})};const [rows,total]=await this.prisma.$transaction([this.prisma.treatmentPlan.findMany({where,select:planSelect,orderBy:[{updatedAt:q.direction??"desc"},{id:"asc"}],skip:offset,take:limit}),this.prisma.treatmentPlan.count({where})]);return paged(rows.map(plan),total,offset,limit)}
 async findById(id:string){const row=await this.prisma.treatmentPlan.findFirst({where:{id,tenantId:this.context.tenantId,...professionalScope(this.context)},select:{...planSelect,items:{where:{tenantId:this.context.tenantId},select:{id:true,procedureId:true,description:true,quantity:true,unitPriceCents:true,discountCents:true,totalCents:true,position:true,procedure:{select:{name:true}}},orderBy:[{position:"asc"},{id:"asc"}]},statusHistory:{where:{tenantId:this.context.tenantId},select:{id:true,fromStatus:true,toStatus:true,changedAt:true,reason:true},orderBy:[{changedAt:"desc"},{id:"desc"}]}}});return row?{...plan(row),sentAt:iso(row.sentAt),acceptedAt:iso(row.acceptedAt),rejectedAt:iso(row.rejectedAt),createdAt:row.createdAt.toISOString(),items:row.items.map(x=>({...x,procedureName:x.procedure?.name??null})),history:row.statusHistory.map(x=>({id:x.id,fromStatus:x.fromStatus?lower(x.fromStatus):null,toStatus:lower(x.toStatus),changedAt:x.changedAt.toISOString(),reason:x.reason}))}:null}
}
const conversationScope=(c:ApplicationContext)=>c.membershipRole==="PROFESSIONAL"?{patient:{appointments:{some:{tenantId:c.tenantId,professionalClinic:{professional:{membershipId:c.membershipId}}}}}}:{};
type ContactRow={patient:{id:string;name:string}|null;lead:{id:string;name:string}|null};
function contact(r:ContactRow){return r.patient?{kind:"patient" as const,id:r.patient.id,name:r.patient.name}:r.lead?{kind:"lead" as const,id:r.lead.id,name:r.lead.name}:{kind:"unlinked" as const,id:null,name:"Contato não vinculado"}}
type ConversationRow=ContactRow&{id:string;channel:string;status:string;integrationId:string|null;lastMessageAt:Date|null;messages?:Array<{bodyPreviewRedacted:string|null}>;_count?:{messages:number}};
function convo(r:ConversationRow){const m=r.messages?.[0];return {id:r.id,channel:lower(r.channel),status:lower(r.status),contact:contact(r),integrationId:r.integrationId,lastMessageAt:iso(r.lastMessageAt),unreadCount:r._count?.messages??0,preview:m?.bodyPreviewRedacted??null}}
export class PrismaConversationReader implements ConversationReader{
 constructor(private context:ApplicationContext,private prisma:PrismaClient=getPrismaClient()){}
 async list(q:Parameters<ConversationReader["list"]>[0]={}){const {offset,limit}=normalizePage({...q,limit:q.limit??30});const range=q.range?parseDateRange(q.range):null;const unread={messages:{some:{tenantId:this.context.tenantId,direction:"INBOUND" as const,readAt:null}}};const where={tenantId:this.context.tenantId,...conversationScope(this.context),...(q.channel?{channel:q.channel.toUpperCase() as never}:{}),...(q.status?{status:q.status.toUpperCase() as never}:{}),...(q.patientId?{patientId:q.patientId}:{}),...(q.leadId?{leadId:q.leadId}:{}),...(q.integrationId?{integrationId:q.integrationId}:{}),...(range?{createdAt:{gte:range.from,lt:range.to}}:{}),...(q.unread?unread:{}),...(q.search?{OR:[{patient:{name:{contains:q.search,mode:"insensitive" as const}}},{lead:{name:{contains:q.search,mode:"insensitive" as const}}},{messages:{some:{tenantId:this.context.tenantId,bodyPreviewRedacted:{contains:q.search,mode:"insensitive" as const}}}}]}:{})};const select={id:true,channel:true,status:true,integrationId:true,lastMessageAt:true,patient:{select:{id:true,name:true}},lead:{select:{id:true,name:true}},messages:{where:{tenantId:this.context.tenantId},select:{bodyPreviewRedacted:true},orderBy:[{createdAt:"desc" as const},{id:"desc" as const}],take:1},_count:{select:{messages:{where:{tenantId:this.context.tenantId,direction:"INBOUND" as const,readAt:null}}}}};const [rows,total]=await this.prisma.$transaction([this.prisma.conversation.findMany({where,select,orderBy:[{lastMessageAt:q.direction??"desc"},{id:"asc"}],skip:offset,take:limit}),this.prisma.conversation.count({where})]);return paged(rows.map(convo),total,offset,limit)}
 async findById(id:string,input:{limit?:number;before?:string}={}){const limit=Math.min(50,Math.max(1,input.limit??50));const before=input.before?new Date(input.before):null;const row=await this.prisma.conversation.findFirst({where:{id,tenantId:this.context.tenantId,...conversationScope(this.context)},select:{id:true,channel:true,status:true,integrationId:true,lastMessageAt:true,patientId:true,leadId:true,patient:{select:{id:true,name:true}},lead:{select:{id:true,name:true}},_count:{select:{messages:{where:{tenantId:this.context.tenantId,direction:"INBOUND",readAt:null}}}},messages:{where:{tenantId:this.context.tenantId,...(before?{createdAt:{lt:before}}:{})},select:{id:true,direction:true,status:true,contentType:true,bodyPreviewRedacted:true,createdAt:true,readAt:true},orderBy:[{createdAt:"desc"},{id:"desc"}],take:limit+1}}});if(!row)return null;const more=row.messages.length>limit;const messages=row.messages.slice(0,limit);return {...convo({...row,messages:[...messages].slice(0,1)}),patientId:row.patientId,leadId:row.leadId,messages:messages.reverse().map(m=>({id:m.id,direction:lower(m.direction),status:lower(m.status),contentType:m.contentType,preview:m.bodyPreviewRedacted,createdAt:m.createdAt.toISOString(),readAt:iso(m.readAt)})),messagePage:{hasMore:more,nextCursor:more?messages.at(-1)?.createdAt.toISOString()??null:null}}}
}
