"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { getApplicationContext } from "@/lib/auth/application-context";
import { requirePermission } from "@/domains/application";
import { createProductionProviderRegistry } from "@/domains/infrastructure/integrations/production-registry";
import { EnvironmentCredentialStore } from "@/domains/infrastructure/integrations/credential-store";
import { IntegrationService } from "@/domains/infrastructure/prisma/integration-service";
import { IntegrationOperationsService } from "@/domains/infrastructure/prisma/integration-operations-service";
const id=z.string().uuid();async function services(){const context=await getApplicationContext();requirePermission(context.membershipRole,"integrations.manage");return {context,integrations:new IntegrationService(context,createProductionProviderRegistry(),new EnvironmentCredentialStore()),operations:new IntegrationOperationsService(context)}}function refresh(slug:string){revalidatePath(`/${slug}/configuracoes`);revalidatePath(`/${slug}/inbox`)}
export async function createIntegration(_:unknown,form:FormData){const s=await services();let configuration={};try{configuration=JSON.parse(String(form.get("configuration")??"{}"))}catch{return {ok:false as const,code:"VALIDATION_ERROR" as const,message:"Configuração inválida."}}const result=await s.integrations.create({provider:form.get("provider"),externalAccountId:form.get("externalAccountId"),credentialReference:form.get("credentialReference"),configuration});if(result.ok)refresh(s.context.tenantSlug);return result}
export async function updateIntegrationConfiguration(_:unknown,form:FormData){const s=await services(),parsed=id.safeParse(form.get("id"));if(!parsed.success)return {ok:false as const,code:"VALIDATION_ERROR" as const,message:"Integração inválida."};let configuration={};try{configuration=JSON.parse(String(form.get("configuration")??"{}"))}catch{return {ok:false as const,code:"VALIDATION_ERROR" as const,message:"Configuração inválida."}}const result=await s.integrations.updateConfiguration(parsed.data,{credentialReference:form.get("credentialReference"),configuration});if(result.ok)refresh(s.context.tenantSlug);return result}
export async function testIntegration(_:unknown,form:FormData){const s=await services(),parsed=id.safeParse(form.get("id"));if(!parsed.success)return {ok:false as const,code:"VALIDATION_ERROR" as const,message:"Integração inválida."};const result=await s.integrations.test(parsed.data);if(result.ok)refresh(s.context.tenantSlug);return result}
async function transition(form:FormData,status:"DISCONNECTED"|"REVOKED"){const s=await services(),parsed=id.safeParse(form.get("id"));if(!parsed.success)return {ok:false as const,code:"VALIDATION_ERROR" as const,message:"Integração inválida."};const result=await s.integrations.transition(parsed.data,status);if(result.ok)refresh(s.context.tenantSlug);return result}
export async function disconnectIntegration(_:unknown,form:FormData){return transition(form,"DISCONNECTED")}
export async function revokeIntegration(_:unknown,form:FormData){return transition(form,"REVOKED")}
export async function retryOutboundMessage(_:unknown,form:FormData){const s=await services(),parsed=id.safeParse(form.get("id"));if(!parsed.success)return {ok:false as const,code:"VALIDATION_ERROR" as const,message:"Mensagem inválida."};const result=await s.operations.retryMessage(parsed.data);if(result.ok)refresh(s.context.tenantSlug);return result}
export async function retryWebhookEvent(_:unknown,form:FormData){const s=await services(),parsed=id.safeParse(form.get("id"));if(!parsed.success)return {ok:false as const,code:"VALIDATION_ERROR" as const,message:"Webhook inválido."};const result=await s.operations.retryWebhook(parsed.data);if(result.ok)refresh(s.context.tenantSlug);return result}
