"use server";

import { revalidatePath } from "next/cache";
import { getApplicationContext } from "@/lib/auth/application-context";
import { getPrismaClient } from "@/lib/db";
import { actionFailure } from "@/domains/application/actions";
import { createPrismaServices } from "@/domains/infrastructure/prisma/factory";
import { canAccessClinic, hasTenantWideClinicAccess } from "@/domains/infrastructure/prisma/clinic-access";
import type { AppointmentStatus } from "@/domains/application/view-models";

const text = (form: FormData, key: string) => String(form.get(key) ?? "").trim();
const nullable = (form: FormData, key: string) => text(form, key) || null;
const checked = (form: FormData, key: string) => form.get(key) === "on";
async function services() { return createPrismaServices(await getApplicationContext()); }
async function refresh(slug: string) { revalidatePath(`/${slug}/agenda`); revalidatePath(`/${slug}/configuracoes`); }
const clinicDenied=()=>actionFailure("ACCESS_DENIED","Você não tem acesso a esta unidade.");
async function verifyClinic(clinicId:string){const context=await getApplicationContext();return canAccessClinic(context,clinicId);}
async function verifyAppointment(id:string){const context=await getApplicationContext();const row=await getPrismaClient().appointment.findFirst({where:{id,tenantId:context.tenantId},select:{clinicId:true}});if(!row)return {ok:false as const,result:actionFailure("NOT_FOUND","Agendamento não encontrado.")};if(!(await canAccessClinic(context,row.clinicId)))return {ok:false as const,result:clinicDenied()};return {ok:true as const};}

export async function saveClinic(form: FormData) { const s=await services(); const input={name:text(form,"name"),slug:text(form,"slug"),timezoneOverride:nullable(form,"timezone"),active:checked(form,"active")}; const id=nullable(form,"id"); const result=id?await s.clinics.update(id,input):await s.clinics.create(input);if(result.ok)await refresh(text(form,"tenantSlug"));return result; }
export async function saveProcedure(form: FormData) { const s=await services();const input={name:text(form,"name"),category:nullable(form,"category"),durationMinutes:Number(text(form,"durationMinutes")),priceCents:Number(text(form,"priceCents")),active:checked(form,"active")};const id=nullable(form,"id");const result=id?await s.procedures.update(id,input):await s.procedures.create(input);if(result.ok)await refresh(text(form,"tenantSlug"));return result; }
export async function saveResource(form: FormData) { const clinicId=text(form,"clinicId");if(!(await verifyClinic(clinicId)))return clinicDenied();const s=await services();const input={clinicId,name:text(form,"name"),type:text(form,"type"),active:checked(form,"active")};const id=nullable(form,"id");const result=id?await s.resources.update(id,input):await s.resources.create(input);if(result.ok)await refresh(text(form,"tenantSlug"));return result; }
export async function saveProfessional(form: FormData) { const clinicIds=form.getAll("clinicIds").map(String);for(const clinicId of clinicIds)if(!(await verifyClinic(clinicId)))return clinicDenied();const s=await services();const input={name:text(form,"name"),specialty:text(form,"specialty"),registrationNumber:nullable(form,"registrationNumber"),registrationRegion:nullable(form,"registrationRegion"),color:nullable(form,"color"),active:checked(form,"active"),clinicIds};const id=nullable(form,"id");const result=id?await s.professionals.update(id,input):await s.professionals.create(input);if(result.ok)await refresh(text(form,"tenantSlug"));return result; }
export async function saveWorkingHours(form: FormData) {const clinicId=text(form,"clinicId");if(!(await verifyClinic(clinicId)))return clinicDenied();const s=await services();const slots=JSON.parse(text(form,"slots")||"[]") as unknown;const result=await s.workingHours.replace({professionalId:text(form,"professionalId"),clinicId,slots});if(result.ok)await refresh(text(form,"tenantSlug"));return result;}
export async function createScheduleBlock(form: FormData) {const context=await getApplicationContext();const clinicId=nullable(form,"clinicId");if(clinicId){if(!(await canAccessClinic(context,clinicId)))return clinicDenied();}else if(!hasTenantWideClinicAccess(context.membershipRole)){return actionFailure("VALIDATION_ERROR","Selecione uma unidade para criar o bloqueio.");}const s=createPrismaServices(context);const result=await s.scheduleBlocks.create({clinicId,professionalId:nullable(form,"professionalId"),resourceId:nullable(form,"resourceId"),startsAt:text(form,"startsAt"),endsAt:text(form,"endsAt"),reason:nullable(form,"reason")});if(result.ok)await refresh(text(form,"tenantSlug"));return result;}
export async function quickCreatePatient(form: FormData) {const s=await services();const result=await s.quickPatients.create({name:text(form,"name"),phoneE164:nullable(form,"phoneE164"),emailNormalized:nullable(form,"email")});if(result.ok)await refresh(text(form,"tenantSlug"));return result;}
export async function createAppointment(form: FormData) {const clinicId=text(form,"clinicId");if(!(await verifyClinic(clinicId)))return clinicDenied();const s=await services();const result=await s.appointments.create({clinicId,patientId:text(form,"patientId"),professionalId:text(form,"professionalId"),procedureId:nullable(form,"procedureId"),resourceId:nullable(form,"resourceId"),startsAt:text(form,"startsAt"),endsAt:text(form,"endsAt"),priceCents:Number(text(form,"priceCents")||0),source:nullable(form,"source")});if(result.ok)await refresh(text(form,"tenantSlug"));return result;}
export async function transitionAppointment(form: FormData) {const access=await verifyAppointment(text(form,"id"));if(!access.ok)return access.result;const s=await services();const result=await s.appointments.transition(text(form,"id"),text(form,"status") as AppointmentStatus,nullable(form,"reason")??undefined);if(result.ok)await refresh(text(form,"tenantSlug"));return result;}
export async function rescheduleAppointment(form: FormData) {const access=await verifyAppointment(text(form,"id"));if(!access.ok)return access.result;const s=await services();const result=await s.appointments.reschedule(text(form,"id"),{startsAt:text(form,"startsAt"),endsAt:text(form,"endsAt")});if(result.ok)await refresh(text(form,"tenantSlug"));return result;}
