"use server";
import {revalidatePath} from "next/cache";import {getApplicationContext} from "@/lib/auth/application-context";import {createPrismaServices} from "@/domains/infrastructure/prisma/factory";
const value=(f:FormData,k:string)=>String(f.get(k)??"").trim(),nullable=(f:FormData,k:string)=>value(f,k)||null;async function setup(){const context=await getApplicationContext();return {context,services:createPrismaServices(context)}}function refresh(slug:string){revalidatePath(`/${slug}/orcamentos`);revalidatePath(`/${slug}/inbox`)}
export async function saveTreatmentPlan(form:FormData){const {context,services}=await setup();let items:unknown=[];try{items=JSON.parse(value(form,"items"))}catch{}const input={patientId:value(form,"patientId"),clinicId:nullable(form,"clinicId"),professionalId:nullable(form,"professionalId"),leadId:nullable(form,"leadId"),title:value(form,"title"),discountCents:Number(value(form,"discountCents")||0),expiresAt:nullable(form,"expiresAt"),items};const id=nullable(form,"id"),result=id?await services.treatmentPlans.update(id,input):await services.treatmentPlans.create(input);if(result.ok)refresh(context.tenantSlug);return result}
export async function duplicateTreatmentPlan(form:FormData){const {context,services}=await setup(),result=await services.treatmentPlans.duplicate(value(form,"id"));if(result.ok)refresh(context.tenantSlug);return result}
export async function transitionTreatmentPlan(form:FormData){const {context,services}=await setup(),result=await services.treatmentPlans.transition(value(form,"id"),{status:value(form,"status"),reason:nullable(form,"reason")});if(result.ok)refresh(context.tenantSlug);return result}
export async function createTreatmentPlanLink(form:FormData){const {context,services}=await setup(),result=await services.treatmentPlans.createPublicLink(value(form,"id"));if(result.ok)refresh(context.tenantSlug);return result}
export async function createConversation(form:FormData){const {context,services}=await setup(),result=await services.conversations.create({channel:value(form,"channel"),patientId:nullable(form,"patientId"),leadId:nullable(form,"leadId"),integrationId:nullable(form,"integrationId")});if(result.ok)refresh(context.tenantSlug);return result}
export async function addConversationMessage(form:FormData){const {context,services}=await setup(),result=await services.conversations.addMessage(value(form,"id"),{preview:value(form,"preview"),internal:form.get("internal")==="true"});if(result.ok)refresh(context.tenantSlug);return result}
export async function markConversationRead(form:FormData){const {context,services}=await setup(),result=await services.conversations.markRead(value(form,"id"));if(result.ok)refresh(context.tenantSlug);return result}
export async function transitionConversation(form:FormData){const {context,services}=await setup(),result=await services.conversations.transition(value(form,"id"),{status:value(form,"status")});if(result.ok)refresh(context.tenantSlug);return result}
export async function linkConversation(form:FormData){const {context,services}=await setup(),result=await services.conversations.link(value(form,"id"),{patientId:nullable(form,"patientId"),leadId:nullable(form,"leadId")});if(result.ok)refresh(context.tenantSlug);return result}
