import {describe,expect,it,vi} from "vitest";vi.mock("server-only",()=>({}));
import {resolveCorrelationId} from "@/lib/observability/correlation";import {redactSensitive,structuredLog} from "@/lib/observability/logger";import {securityHeaders,assertSameOrigin} from "@/lib/security/http";import {getOperationalMode,assertOperationalAction,resolveTenantOperationalAccess} from "@/lib/security/operational-mode";import {hashRateLimitIdentity} from "@/lib/security/rate-limit";import {validateRuntimeConfiguration} from "@/lib/runtime/config";import {GET as live} from "@/app/api/health/live/route";
describe("pilot operational hardening",()=>{
 it("accepts bounded request ids and replaces invalid input",()=>{expect(resolveCorrelationId("req_123")).toBe("req_123");expect(resolveCorrelationId("x".repeat(100))).toMatch(/^[0-9a-f-]{36}$/)});
 it("redacts forbidden keys and logs only allowlisted context",()=>{expect(redactSensitive({email:"x@y.z",tenantId:"t",payload:{secret:"x"}})).toEqual({tenantId:"t"});const spy=vi.spyOn(console,"info").mockImplementation(()=>{});expect(structuredLog("info","test",{tenantId:"t"})).toMatchObject({event:"test",tenantId:"t"});spy.mockRestore()});
 it("sets hardened headers and HSTS only for production HTTPS",()=>{expect(securityHeaders({NODE_ENV:"test"})["Strict-Transport-Security"]).toBeUndefined();expect(securityHeaders({APP_ENV:"production",PUBLIC_APP_ORIGIN:"https://app.example",DATABASE_URL:"x",BETTER_AUTH_SECRET:"x",RATE_LIMIT_HASH_KEY:"x"})["Strict-Transport-Security"]).toContain("max-age");expect(securityHeaders({NODE_ENV:"test"})["Content-Security-Policy"]).toContain("object-src 'none'")});
 it("enforces canonical origin",()=>{expect(()=>assertSameOrigin(new Request("https://app.example/api",{headers:{origin:"https://evil.example",host:"app.example"}}),{APP_ENV:"production",PUBLIC_APP_ORIGIN:"https://app.example"})).toThrow("CSRF_ORIGIN_DENIED")});
 it("enforces operational mode and tenant/pilot access server-side",()=>{expect(getOperationalMode({APP_ENV:"test",OPERATIONAL_MODE:"NORMAL"})).toBe("NORMAL");expect(()=>assertOperationalAction("clinical-write",{APP_ENV:"test",OPERATIONAL_MODE:"READ_ONLY"})).toThrow("OPERATION_READ_ONLY");expect(resolveTenantOperationalAccess({status:"SUSPENDED",slug:"a"},"clinical-write",{APP_ENV:"test"}).allowed).toBe(false);expect(resolveTenantOperationalAccess({status:"ACTIVE",slug:"a"},"clinical-write",{APP_ENV:"test",PILOT_MODE:"true",PILOT_TENANT_SLUGS:"b"}).allowed).toBe(false)});
 it("HMACs identities without retaining PII and fails closed without key",()=>{const env={RATE_LIMIT_HASH_KEY:"a".repeat(32)};const hash=hashRateLimitIdentity(["person@example.com","tenant"],env);expect(hash).toMatch(/^[a-f0-9]{64}$/);expect(hash).not.toContain("person");expect(()=>hashRateLimitIdentity(["x"],{})).toThrow("A configuração operacional não está disponível")});
 it("keeps build-time config lazy and flags unsafe production",()=>{expect(validateRuntimeConfiguration({NODE_ENV:"test"}).valid).toBe(true);expect(validateRuntimeConfiguration({APP_ENV:"production",PUBLIC_APP_ORIGIN:"http://localhost"}).valid).toBe(false)});
 it("serves liveness without database and with no-store",()=>{const response=live({headers:new Headers()} as never);expect(response.status).toBe(200);expect(response.headers.get("cache-control")).toBe("no-store")});
});
