import {describe,expect,it,vi} from "vitest";vi.mock("server-only",()=>({}));
import {render,screen} from "@testing-library/react";import {getExternalEffectsMode,getRuntimeEnvironment,validateRuntimeConfiguration} from "@/lib/runtime/config";import {assertExternalEffectAllowed,ExternalEffectDisabledError} from "@/lib/runtime/external-effects";import {StagingBanner} from "@/components/layout/staging-banner";import {releaseManifest} from "@/scripts/ops-release-manifest";import {assertStagingSeedInput,seedSyntheticStaging} from "@/scripts/seed-staging";import {runSmoke} from "@/scripts/ops-smoke";
const staging={APP_ENV:"staging",NEXT_PUBLIC_APP_URL:"https://staging.example.test",BETTER_AUTH_URL:"https://staging.example.test",BETTER_AUTH_TRUSTED_ORIGINS:"https://staging.example.test",BETTER_AUTH_SECRET:"a".repeat(32),DATABASE_URL:"configured",DIRECT_DATABASE_URL:"configured",FIELD_ENCRYPTION_KEY:"x".repeat(32),RATE_LIMIT_HASH_KEY:"r".repeat(32),OPERATIONAL_MODE:"NORMAL",EXTERNAL_EFFECTS_MODE:"DISABLED",ASAAS_ENVIRONMENT:"sandbox"};
describe("controlled staging",()=>{
 it("classifies environments fail-closed",()=>{expect(getRuntimeEnvironment({APP_ENV:"staging",NODE_ENV:"production"})).toBe("staging");expect(getRuntimeEnvironment({NODE_ENV:"production"})).toBe("production");expect(getRuntimeEnvironment({})).toBe("development");expect(()=>getRuntimeEnvironment({APP_ENV:"prodution"})).toThrow();expect(()=>getRuntimeEnvironment({APP_ENV:"preview"})).toThrow()});
 it("requires the staging contract and HTTPS",()=>{expect(validateRuntimeConfiguration(staging).valid).toBe(true);expect(validateRuntimeConfiguration({...staging,NEXT_PUBLIC_APP_URL:"http://bad.test"}).valid).toBe(false);expect(validateRuntimeConfiguration({...staging,ASAAS_ENVIRONMENT:"production"}).issues).toContain("ASAAS_PRODUCTION_DENIED")});
 it("disables external effects by default and only admits explicit sandbox",()=>{expect(getExternalEffectsMode({APP_ENV:"staging"})).toBe("DISABLED");expect(()=>assertExternalEffectAllowed("sandbox",{APP_ENV:"staging"})).toThrow(ExternalEffectDisabledError);expect(()=>assertExternalEffectAllowed("production",{APP_ENV:"staging",EXTERNAL_EFFECTS_MODE:"SANDBOX"})).toThrow();expect(()=>assertExternalEffectAllowed("sandbox",{APP_ENV:"staging",EXTERNAL_EFFECTS_MODE:"SANDBOX"})).not.toThrow()});
 it("renders banner only in staging",()=>{const {rerender}=render(<StagingBanner env={{APP_ENV:"staging"}}/>);expect(screen.getByRole("status")).toHaveTextContent("AMBIENTE DE HOMOLOGAÇÃO");rerender(<StagingBanner env={{APP_ENV:"production"}}/>);expect(screen.queryByRole("status")).toBeNull()});
 it("sanitizes and deterministically emits release metadata",()=>{const env={APP_ENV:"test",BUILD_SHA:"a".repeat(40),RELEASE_ID:"release-1",BUILD_TIMESTAMP:"2026-08-04T00:00:00Z"};expect(releaseManifest(env)).toBe(releaseManifest(env));expect(releaseManifest({...env,RELEASE_ID:"secret value!"})).not.toContain("secret value")});
 it("seed refuses non-staging and is idempotent without credentials",async()=>{expect(()=>assertStagingSeedInput({APP_ENV:"development"})).toThrow("STAGING_ONLY");expect(()=>assertStagingSeedInput({APP_ENV:"production"})).toThrow("STAGING_ONLY");const prisma={tenant:{findUnique:vi.fn().mockResolvedValue({id:"t"})},procedure:{findFirst:vi.fn().mockResolvedValue({id:"p"}),create:vi.fn()}};await seedSyntheticStaging(prisma as never,"synthetic");expect(prisma.procedure.create).not.toHaveBeenCalled();expect(prisma).not.toHaveProperty("user")});
 it("smoke rejects degraded readiness",async()=>{const fetcher=vi.fn().mockImplementation((url:URL)=>Promise.resolve(new Response(JSON.stringify({status:url.pathname.endsWith("ready")?"degraded":"ok"}),{status:url.pathname.endsWith("ready")?503:200})));await expect(runSmoke(new URL("https://staging.example.test"),fetcher as never)).rejects.toThrow()});
});
