"use client";
import { Download, Filter, Save, Trash2, X } from "lucide-react";
import { useState } from "react";
import { clinicUnits,defaultReportFilters,professionalPerformance,reportMetrics,reportPeriodLabels,reportSeries,scheduleProcedures,scheduleProfessionals,unitPerformance,type ReportFilters,type SavedReportView } from "@/domains/demo";
import { formatCurrency } from "@/lib/formatting/currency";
import { Button } from "@/components/ui/button";
import { MetricCard } from "@/components/shared/metric-card";
const sections={overview:"Visão geral",financial:"Financeiro",schedule:"Agenda",patients:"Pacientes",commercial:"Comercial",service:"Atendimento",professionals:"Profissionais",units:"Unidades"} as const; type Section=keyof typeof sections;
const format=(value:number,type:string)=>type==="currency"?formatCurrency(value):type==="percent"?`${value}%`:type==="minutes"?`${value} min`:String(value);
const selectClass="min-h-10 rounded-md border border-line bg-bg-elev px-3 text-sm text-ink";
export function ReportsView(){const[section,setSection]=useState<Section>("overview"),[filters,setFilters]=useState<ReportFilters>(defaultReportFilters),[filtersOpen,setFiltersOpen]=useState(false),[views,setViews]=useState<SavedReportView[]>([]),[feedback,setFeedback]=useState(""),[exportOpen,setExportOpen]=useState(false),[selectedUnits,setSelectedUnits]=useState(["centro","leste"]);const metrics=reportMetrics[section]??reportMetrics.overview!;const active=Object.entries(filters).filter(([k,v])=>k!=="period"&&v).length;
 const update=<K extends keyof ReportFilters>(key:K,value:ReportFilters[K])=>setFilters(f=>({...f,[key]:value}));const saveView=()=>{const view={id:`view-${views.length+1}`,name:`Visão ${views.length+1} · ${sections[section]}`,filters:{...filters}};setViews(v=>[...v,view]);setFeedback("Visão salva somente nesta sessão.")};
 return <div className="mx-auto max-w-7xl space-y-6"><header className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="font-mono text-[11px] uppercase tracking-[.15em] text-primary">Inteligência · Clínica Aurora</p><h1 className="mt-2 font-display text-4xl md:text-5xl">Relatórios</h1><p className="mt-2 text-sm text-ink-muted">Dados fictícios consolidados da agenda, CRM, pacientes, orçamentos e Inbox.</p><p className="mt-1 text-xs text-ink-dim">Atualizado em 20/09/2026 às 16:00 · dados demonstrativos</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>setFiltersOpen(v=>!v)}><Filter className="mr-2" size={15}/>Filtros {active?`(${active})`:""}</Button><div className="relative"><Button variant="outline" onClick={()=>setExportOpen(v=>!v)}><Download className="mr-2" size={15}/>Exportar</Button>{exportOpen&&<div className="absolute right-0 z-20 mt-2 w-48 rounded-md border border-line bg-bg-elev p-2 shadow-soft">{["PDF","Excel","CSV","Impressão"].map(x=><button key={x} className="block w-full rounded p-2 text-left text-sm hover:bg-bg-alt" onClick={()=>{setFeedback(x==="CSV"?"CSV fictício preparado localmente.":`${x}: exportação simulada, nenhum arquivo externo foi criado.`);setExportOpen(false)}}>{x}</button>)}</div>}</div><Button onClick={saveView}><Save className="mr-2" size={15}/>Salvar visão</Button></div></header>
 {feedback&&<div role="status" aria-live="polite" className="flex justify-between rounded-md border border-primary/30 bg-primary/5 p-3 text-sm"><span>{feedback}</span><button aria-label="Fechar aviso" onClick={()=>setFeedback("")}><X size={15}/></button></div>}
 <div className="flex flex-wrap gap-2 rounded-lg border border-line bg-bg-alt p-3"><label className="text-xs text-ink-muted">Período <select aria-label="Período" className={`${selectClass} ml-2`} value={filters.period} onChange={e=>update("period",e.target.value as ReportFilters["period"])}>{Object.entries(reportPeriodLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="text-xs text-ink-muted">Unidade <select aria-label="Unidade" className={`${selectClass} ml-2`} value={filters.unitId} onChange={e=>update("unitId",e.target.value)}><option value="">Todas</option>{clinicUnits.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="text-xs text-ink-muted">Profissional <select aria-label="Profissional" className={`${selectClass} ml-2`} value={filters.professionalId} onChange={e=>update("professionalId",e.target.value)}><option value="">Todos</option>{scheduleProfessionals.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="ml-auto flex items-center gap-2 text-xs"><input type="checkbox" defaultChecked/> Comparar período anterior</label></div>
 {filters.period==="custom"&&<div className="grid gap-3 rounded-md border border-line p-4 sm:grid-cols-2"><label className="text-xs">Data inicial<input aria-label="Data inicial" type="date" className={`${selectClass} mt-1 w-full`} onChange={e=>update("start",e.target.value)}/></label><label className="text-xs">Data final<input aria-label="Data final" type="date" className={`${selectClass} mt-1 w-full`} onChange={e=>update("end",e.target.value)}/></label></div>}
 {filtersOpen&&<section aria-label="Filtros avançados" className="grid gap-3 rounded-lg border border-line bg-bg-alt p-4 sm:grid-cols-2 lg:grid-cols-4">{[["procedureId","Procedimento",scheduleProcedures.map(x=>[x.id,x.name])],["channel","Canal",["WhatsApp","Instagram","E-mail"].map(x=>[x,x])],["origin","Origem",["Google","Indicação","CRM","Inbox"].map(x=>[x,x])],["status","Status",["Confirmado","Realizado","Pendente"].map(x=>[x,x])],["owner","Responsável",["Ana Souza","Bruno Melo","Carla Dias"].map(x=>[x,x])]].map(([key,label,options])=><label key={key as string} className="text-xs">{label as string}<select className={`${selectClass} mt-1 w-full`} value={String(filters[key as keyof ReportFilters]??"")} onChange={e=>update(key as keyof ReportFilters,e.target.value)}><option value="">Todos</option>{(options as string[][]).map(o=><option key={o[0]} value={o[0]}>{o[1]}</option>)}</select></label>)}<button className="self-end p-3 text-sm text-primary" onClick={()=>setFilters(defaultReportFilters)}>Limpar filtros</button></section>}
 {active>0&&<div className="flex flex-wrap gap-2">{Object.entries(filters).filter(([k,v])=>k!=="period"&&v).map(([k,v])=><button key={k} className="rounded-full border border-line px-3 py-1 text-xs" onClick={()=>update(k as keyof ReportFilters,"")}>{String(v)} ×</button>)}</div>}
 {views.length>0&&<section aria-label="Visões salvas" className="flex flex-wrap items-center gap-2"><span className="text-xs text-ink-dim">Visões salvas:</span>{views.map(v=><span key={v.id} className="inline-flex rounded-md border border-line"><button className="px-3 py-2 text-xs" onClick={()=>setFilters(v.filters)}>{v.name}</button><button aria-label={`Remover ${v.name}`} className="border-l border-line px-2" onClick={()=>setViews(x=>x.filter(i=>i.id!==v.id))}><Trash2 size={12}/></button></span>)}</section>}
 <div role="tablist" aria-label="Categorias de relatórios" className="flex gap-1 overflow-x-auto border-b border-line">{Object.entries(sections).map(([id,label])=><button role="tab" aria-selected={section===id} key={id} onClick={()=>setSection(id as Section)} className={`min-h-11 whitespace-nowrap border-b-2 px-3 text-sm ${section===id?"border-primary text-ink":"border-transparent text-ink-muted"}`}>{label}</button>)}</div>
 <section aria-label={`Indicadores de ${sections[section]}`} className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{metrics.map(m=><MetricCard key={m.id} label={m.label} value={format(m.value,m.format)} detail={`${m.value>=m.previous?"↑":"↓"} ${Math.abs(Math.round((m.value-m.previous)/(m.previous||1)*100))}% versus período anterior${m.goal?` · meta ${format(m.goal,m.format)}`:""}`}/>)}</section>
 {section==="professionals"?<PerformanceTable/>:section==="units"?<UnitComparison selected={selectedUnits} onChange={setSelectedUnits}/>:<Charts section={section}/>} </div>}
function Charts({section}:{section:Section}){const labels:Record<string,string>={overview:"Receita e metas",financial:"Evolução mensal e orçamento versus realizado",schedule:"Capacidade e horários de pico",patients:"Origem, faixa etária e retenção",commercial:"Funil, origem e motivos de perda",service:"Volume por canal e horários de demanda"};return <div className="grid gap-6 lg:grid-cols-2"><section className="card-surface p-5"><h2 className="font-display text-2xl">{labels[section]}</h2><p className="mt-1 text-sm text-ink-muted">Comparativo acessível dos últimos seis períodos.</p><div className="mt-8 flex h-52 items-end gap-3" aria-label="Gráfico de barras realizado e previsto">{reportSeries[0]!.values.map((v,i)=><div key={i} className="flex flex-1 items-end gap-1"><span className="w-1/2 rounded-t bg-primary" style={{height:`${v/2}%`}}/><span className="w-1/2 rounded-t bg-info/60" style={{height:`${reportSeries[1]!.values[i]!/2}%`}}/></div>)}</div><p className="sr-only">A série realizada cresce de 124 para 187 e permanece abaixo da previsão de 224.</p><div className="mt-3 flex gap-4 text-xs"><span>● Realizado</span><span className="text-info">● Previsto</span></div></section><section className="card-surface p-5"><h2 className="font-display text-2xl">Distribuição e destaques</h2><p className="mt-1 text-sm text-ink-muted">Composição fictícia por origem, status ou canal.</p><div className="mx-auto mt-8 size-44 rounded-full" role="img" aria-label="Distribuição: principal 58%, secundária 27%, demais 15%" style={{background:"conic-gradient(hsl(var(--accent)) 0 58%,hsl(var(--info)) 58% 85%,hsl(var(--line-strong)) 85%)"}}><div className="relative left-9 top-9 flex size-28 items-center justify-center rounded-full bg-bg-alt font-display text-2xl">58%</div></div><div className="mt-6 grid gap-2 text-sm"><p className="rounded-md bg-positive/10 p-3">Destaque positivo: comparecimento avançou 4 pontos.</p><p className="rounded-md bg-danger/10 p-3">Alerta: 7 atendimentos ultrapassaram o SLA.</p><p className="rounded-md border border-line p-3">Meta mensal: 81% concluída.</p></div></section></div>}
function PerformanceTable(){return <section className="overflow-x-auto rounded-lg border border-line"><table className="w-full min-w-[900px] text-left text-sm"><caption className="sr-only">Desempenho por profissional</caption><thead className="bg-bg-elev text-xs"><tr>{["Profissional","Atendimentos","Receita","Ticket","Ocupação","Comparecimento","Conversão","Avaliação","Horas"].map(x=><th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{professionalPerformance.map(p=><tr className="border-t border-line" key={p.id}><td className="p-3 font-medium">{p.name}</td><td>{p.appointments}</td><td>{formatCurrency(p.revenueCents)}</td><td>{formatCurrency(p.averageTicketCents)}</td><td>{p.occupancy}%</td><td>{p.attendance}%</td><td>{p.conversion}%</td><td>{p.rating} / 5</td><td>{p.usedHours}h / {p.availableHours}h</td></tr>)}</tbody></table></section>}
function UnitComparison({selected,onChange}:{selected:string[];onChange:(x:string[])=>void}){return <section className="space-y-4"><div className="flex gap-3">{unitPerformance.map(u=><label key={u.id} className="rounded-md border border-line p-3 text-sm"><input type="checkbox" checked={selected.includes(u.id)} onChange={()=>onChange(selected.includes(u.id)?selected.filter(x=>x!==u.id):[...selected,u.id])}/> {u.name}</label>)}</div>{selected.length<2?<div className="rounded-md border border-warm/30 p-8 text-center">Selecione duas ou mais unidades para comparar.</div>:<div className="grid gap-4 md:grid-cols-2">{unitPerformance.filter(u=>selected.includes(u.id)).map(u=><article className="card-surface p-5" key={u.id}><h2 className="font-display text-2xl">{u.name}</h2><dl className="mt-4 grid grid-cols-2 gap-3 text-sm">{[["Receita",formatCurrency(u.revenueCents)],["Agenda",u.appointments],["Pacientes",u.patients],["Conversão",`${u.conversion}%`],["Ocupação",`${u.occupancy}%`],["Faltas",u.noShows],["Atendimento",u.conversations],["Leads",u.leads]].map(([k,v])=><div key={k}><dt className="text-ink-dim">{k}</dt><dd className="font-medium">{v}</dd></div>)}</dl></article>)}</div>}</section>}
