import { Download } from "lucide-react";
import { DataTable } from "@/components/shared/data-table";
import { FilterButton } from "@/components/shared/filter-button";
import { MetricCard } from "@/components/shared/metric-card";
import { PageHeader } from "@/components/shared/page-header";
import { SectionHeader } from "@/components/shared/section-header";

const rows = [{ name: "Avaliações", scheduled: 64, completed: 58, conversion: "63%" }, { name: "Ortodontia", scheduled: 41, completed: 38, conversion: "71%" }, { name: "Implantodontia", scheduled: 27, completed: 24, conversion: "54%" }];
export function ReportsView() { return <div className="mx-auto max-w-7xl space-y-7"><PageHeader eyebrow="Inteligência · Setembro 2026" title="Relatórios" description="Visão analítica resumida da Clínica Aurora com números exclusivamente fictícios." /><div className="flex flex-wrap gap-2"><FilterButton>Período: este mês</FilterButton><FilterButton>Unidade: todas</FilterButton><button type="button" className="ml-auto inline-flex min-h-10 items-center gap-2 rounded-md border border-line px-4 text-sm text-ink-muted"><Download aria-hidden="true" size={15} />Exportar</button></div><section aria-label="Indicadores dos relatórios" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Receita" value="R$ 187,4 mil" detail="+12% em relação ao período anterior" /><MetricCard label="Ocupação" value="82%" detail="314 horas disponíveis" /><MetricCard label="Conversão" value="58%" detail="18 propostas aceitas" /><MetricCard label="Ticket médio" value="R$ 1.420" detail="Considera atendimentos concluídos" /></section><section className="card-surface p-5"><SectionHeader title="Receita por período" description="Evolução semanal da operação simulada" /><div aria-label="Gráfico de receita por semana" className="mt-8 flex h-56 items-end gap-3">{[48, 66, 57, 82, 74, 91, 78, 96].map((height, index) => <div key={index} className="group flex flex-1 flex-col justify-end gap-2"><div className="rounded-t bg-info/70 group-hover:bg-info" style={{ height: `${height}%` }} /><span className="text-center font-mono text-[9px] text-ink-dim">S{index + 1}</span></div>)}</div></section><section className="space-y-4"><SectionHeader title="Desempenho por serviço" description="Comparativo analítico da demonstração" /><DataTable label="Desempenho por serviço" headings={["Serviço", "Agendados", "Concluídos", "Conversão"]}>{rows.map((row) => <tr key={row.name}><td className="p-4 font-medium">{row.name}</td><td className="px-3 font-mono">{row.scheduled}</td><td className="px-3 font-mono">{row.completed}</td><td className="px-3 text-primary">{row.conversion}</td></tr>)}</DataTable></section></div>; }
