import "server-only";
import {z} from "zod";import type {PrismaClient} from "@/generated/prisma/client";import type {PlatformContext} from "@/domains/application/platform";import {canManagePlatformOperator,requirePlatformPermission} from "@/domains/application/platform";
const reason=z.string().trim().min(10).max(500);const id=z.string().uuid();
export class PlatformAdministrationService{constructor(private prisma:PrismaClient){}
 async changeTenantStatus(c:PlatformContext,input:unknown){requirePlatformPermission(c.role,"platform.tenants.manage_status");const data=z.object({tenantId:id,status:z.enum(["ACTIVE","SUSPENDED"]),reason}).parse(input);return this.prisma.$transaction(async tx=>{const row=await tx.tenant.update({where:{id:data.tenantId},data:{status:data.status}});await tx.auditLog.create({data:{tenantId:row.id,actorUserId:c.userId,action:data.status==="SUSPENDED"?"platform.tenant.suspended":"platform.tenant.reactivated",resourceType:"Tenant",resourceId:row.id,outcome:"SUCCESS",metadata:{reasonCode:"OPERATOR_CONFIRMED"}}});return row})}
 async changeUserStatus(c:PlatformContext,input:unknown){requirePlatformPermission(c.role,"platform.users.manage_status");const data=z.object({userId:id,status:z.enum(["ACTIVE","SUSPENDED","DISABLED"]),reason,confirmation:z.string()}).parse(input);if(data.userId===c.userId)throw new Error("SELF_STATUS_CHANGE_DENIED");if(data.status==="DISABLED"&&data.confirmation!=="DESABILITAR USUARIO")throw new Error("CONFIRMATION_REQUIRED");return this.prisma.$transaction(async tx=>{await tx.$executeRaw`SELECT pg_advisory_xact_lock(350035)`;const target=await tx.user.findUnique({where:{id:data.userId},select:{platformOperator:{select:{role:true,status:true}}}});if(target?.platformOperator?.role==="PLATFORM_OWNER"&&data.status!=="ACTIVE"&&c.role!=="PLATFORM_OWNER")throw new Error("PLATFORM_OWNER_PROTECTED");const row=await tx.user.update({where:{id:data.userId},data:{status:data.status}});if(data.status!=="ACTIVE"){const usable=await tx.platformOperator.count({where:{role:"PLATFORM_OWNER",status:"ACTIVE",user:{status:"ACTIVE",emailVerified:true}}});if(usable<1)throw new Error("LAST_PLATFORM_OWNER_REQUIRED")}await tx.auditLog.create({data:{actorUserId:c.userId,action:data.status==="ACTIVE"?"platform.user.reactivated":"platform.user.suspended",resourceType:"User",resourceId:row.id,outcome:"SUCCESS"}});return row},{isolationLevel:"Serializable"})}
 async revokeSessions(c:PlatformContext,userId:unknown){requirePlatformPermission(c.role,"platform.sessions.revoke");const target=id.parse(userId);if(target===c.userId)throw new Error("SELF_REVOCATION_DENIED");return this.prisma.$transaction(async tx=>{const result=await tx.authSession.deleteMany({where:{userId:target}});await tx.auditLog.create({data:{actorUserId:c.userId,action:"platform.sessions.revoked",resourceType:"User",resourceId:target,outcome:"SUCCESS",metadata:{count:result.count}}});return result})}
 async changeOperator(c:PlatformContext,input:unknown){requirePlatformPermission(c.role,"platform.operators.manage");const data=z.object({operatorId:id,role:z.enum(["PLATFORM_OWNER","PLATFORM_ADMIN","SUPPORT","BILLING","READONLY"]).optional(),status:z.enum(["ACTIVE","SUSPENDED","REVOKED"]).optional()}).parse(input);if(data.operatorId===c.operatorId&&data.role)throw new Error("SELF_PROMOTION_DENIED");return this.prisma.$transaction(async tx=>{await tx.$executeRaw`SELECT pg_advisory_xact_lock(350035)`;const target=await tx.platformOperator.findUnique({where:{id:data.operatorId}});if(!target||!canManagePlatformOperator(c.role,target.role,data.role))throw new Error("PLATFORM_ACCESS_DENIED");const row=await tx.platformOperator.update({where:{id:target.id},data:{...(data.role?{role:data.role}:{}),...(data.status?{status:data.status}:{})}});const usable=await tx.platformOperator.count({where:{role:"PLATFORM_OWNER",status:"ACTIVE",user:{status:"ACTIVE",emailVerified:true}}});if(usable<1)throw new Error("LAST_PLATFORM_OWNER_REQUIRED");await tx.auditLog.create({data:{actorUserId:c.userId,action:data.status==="REVOKED"?"platform.operator.revoked":data.status==="SUSPENDED"?"platform.operator.suspended":"platform.operator.role_changed",resourceType:"PlatformOperator",resourceId:row.id,outcome:"SUCCESS"}});return row},{isolationLevel:"Serializable"})}
}
