export type AdminTenantStatus="Trial"|"Ativo"|"Inadimplente"|"Bloqueado"|"Cancelado";
export interface AdminTenant{id:string;company:string;plan:string;status:AdminTenantStatus;users:number;units:number;createdAt:string;lastAccess:string;usage:number;billing:string;health:"Saudável"|"Atenção"|"Crítico";note:string}
export interface AdminUser{id:string;name:string;tenantId:string;emailMasked:string;role:string;status:"Ativo"|"Suspenso";lastAccess:string;sessions:number;mfa:boolean}
export interface AdminSubscription{id:string;tenantId:string;plan:string;status:string;priceCents:number;cycle:string;nextCharge:string;failures:number;attempts:number;method:string}
export interface SystemService{id:string;name:string;status:"Operacional"|"Degradado"|"Incidente"|"Manutenção";latencyMs:number;errorRate:number}
export interface SystemJob{id:string;name:string;type:string;status:"Concluído"|"Executando"|"Falhou";attempts:number;durationMs:number;startedAt:string;completedAt?:string;sanitizedError?:string}
export interface SupportTicket{id:string;subject:string;tenant:string;priority:"Baixa"|"Normal"|"Alta"|"Urgente";owner:string;slaDueAt:string;status:"Aberto"|"Em atendimento"|"Resolvido";category:string;updatedAt:string}
export interface FeatureFlag{id:string;name:string;description:string;enabled:boolean;scope:string;tenants:number;environment:"demo";updatedBy:string;updatedAt:string}
export const adminTenants:AdminTenant[]=["Aurora","Horizonte","Instituto Sorriso","Vida Plena","Odonto Prime","Bem Estar"].map((x,i)=>({id:`tenant-${i+1}`,company:`Clínica ${x}`,plan:["Pro","Essencial","Escala"][i%3]!,status:(['Ativo','Trial','Inadimplente','Bloqueado','Ativo','Cancelado'] as AdminTenantStatus[])[i]!,users:4+i*3,units:1+i%3,createdAt:`2026-0${i+1}-12`,lastAccess:i===3?"Há 9 dias":"Hoje",usage:42+i*8,billing:i===2?"Pendente":"Em dia",health:i===3?"Crítico":i===2?"Atenção":"Saudável",note:""}));
export const adminUsers:AdminUser[]=adminTenants.flatMap((t,i)=>[{id:`user-${i}`,name:`Usuário administrativo ${i+1}`,tenantId:t.id,emailMasked:`u***${i+1}@exemplo.test`,role:i%2?"Gestor":"Proprietário",status:i===3?"Suspenso":"Ativo",lastAccess:t.lastAccess,sessions:i%3,mfa:i%2===0}]);
export const adminSubscriptions:AdminSubscription[]=adminTenants.map((t,i)=>({id:`sub-${i}`,tenantId:t.id,plan:t.plan,status:t.status,priceCents:[29900,14900,49900][i%3]!,cycle:i%2?"Anual":"Mensal",nextCharge:"2026-10-05",failures:i===2?2:0,attempts:i===2?3:0,method:"Cartão •••• 4242 (fictício)"}));
export const systemServices:SystemService[]=["Aplicação","Banco","Autenticação","Filas","E-mail","Mensagens","Webhooks","Storage","Jobs"].map((name,i)=>({id:`svc-${i}`,name,status:i===5?"Degradado":"Operacional",latencyMs:38+i*17,errorRate:i===5?2.4:0.1}));
export const systemJobs:SystemJob[]=[{id:"job-1",name:"Resumo diário",type:"notification",status:"Concluído",attempts:1,durationMs:842,startedAt:"09:00",completedAt:"09:00"},{id:"job-2",name:"Sincronização simulada",type:"integration",status:"Falhou",attempts:3,durationMs:2200,startedAt:"09:12",completedAt:"09:14",sanitizedError:"PROVIDER_UNAVAILABLE — identificadores removidos"},{id:"job-3",name:"Consolidação analítica",type:"report",status:"Executando",attempts:1,durationMs:0,startedAt:"09:40"}];
export const supportTickets:SupportTicket[]=[{id:"SUP-1042",subject:"Dúvida sobre agenda",tenant:"Clínica Aurora",priority:"Alta",owner:"Lia",slaDueAt:"2026-09-20T18:00:00Z",status:"Em atendimento",category:"Produto",updatedAt:"Há 12 min"},{id:"SUP-1041",subject:"Importação demonstrativa",tenant:"Clínica Horizonte",priority:"Normal",owner:"Não atribuído",slaDueAt:"2026-09-21T12:00:00Z",status:"Aberto",category:"Dados",updatedAt:"Há 45 min"}];
export const featureFlags:FeatureFlag[]=["reports_v2","calendar_capacity","inbox_satisfaction","billing_portal"].map((name,i)=>({id:`flag-${i}`,name,description:"Recurso controlado apenas na demonstração.",enabled:i<2,scope:i%2?"Tenants selecionados":"Global",tenants:i*3,environment:"demo",updatedBy:"Equipe FlipSchedule",updatedAt:"2026-09-20"}));
export const filterAdminTenants=(items:readonly AdminTenant[],query:string,status="")=>items.filter(t=>(!query||t.company.toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR")))&&(!status||t.status===status));
export const calculateDemoMrr=(subscriptions:readonly AdminSubscription[])=>subscriptions.filter(s=>s.status==="Ativo").reduce((sum,s)=>sum+(s.cycle==="Anual"?Math.round(s.priceCents/12):s.priceCents),0);
export const calculateDemoChurn=(items:readonly AdminTenant[])=>items.length?Math.round(items.filter(t=>t.status==="Cancelado").length/items.length*1000)/10:0;
export const aggregateSystemHealth=(items:readonly SystemService[])=>items.some(s=>s.status==="Incidente")?"Incidente":items.some(s=>s.status==="Degradado")?"Degradado":"Operacional";
export const detectFailedJobs=(items:readonly SystemJob[])=>items.filter(j=>j.status==="Falhou");
export const calculateSupportSla=(ticket:SupportTicket,now="2026-09-20T16:00:00Z")=>({remainingMinutes:Math.round((new Date(ticket.slaDueAt).getTime()-new Date(now).getTime())/60000),breached:new Date(ticket.slaDueAt)<new Date(now)});
export const filterFeatureFlags=(items:readonly FeatureFlag[],query:string,enabled?:boolean)=>items.filter(f=>(!query||`${f.name} ${f.description}`.toLowerCase().includes(query.toLowerCase()))&&(enabled===undefined||f.enabled===enabled));
