export type ConversationStatus="new"|"open"|"waiting_patient"|"waiting_team"|"resolved"|"archived";
export type ConversationPriority="low"|"normal"|"high"|"urgent";
export type ConversationChannel="WhatsApp"|"Instagram"|"Messenger"|"Site"|"E-mail"|"Telefone"|"Interno";
export type MessageType="text"|"image"|"document"|"audio"|"location"|"event"|"internal_note";
export interface ConversationMessage{id:string;direction:"incoming"|"outgoing"|"internal";type:MessageType;body:string;sentAt:string;deliveryStatus:"sent"|"delivered"|"read"|"failed";author:string;pinned?:boolean}
export type InternalNote=ConversationMessage&{direction:"internal";type:"internal_note"};
export interface ConversationTag{id:string;name:string}
export interface QuickReply{id:string;title:string;category:string;body:string}
export interface Conversation{id:string;patientId?:string|undefined;leadId?:string|undefined;treatmentPlanId?:string|undefined;appointmentId?:string|undefined;contactName:string;phone:string;email:string;channel:ConversationChannel;status:ConversationStatus;priority:ConversationPriority;assignee:string;unit:"Centro"|"Zona Leste";origin:string;tags:ConversationTag[];unreadCount:number;lastMessageAt:string;firstResponseAt?:string|undefined;messages:ConversationMessage[];lastVisitAt?:string|undefined;nextAppointmentAt?:string|undefined;potentialValueCents:number;consents:string[];notes:string}
export interface ConversationFilters{query:string;channel:string;status:string;assignee:string;unit:string;priority:string;tag:string;unread:boolean;overdue:boolean;unassigned:boolean;archived:boolean;patient:boolean;lead:boolean}
export const emptyConversationFilters:ConversationFilters={query:"",channel:"",status:"",assignee:"",unit:"",priority:"",tag:"",unread:false,overdue:false,unassigned:false,archived:false,patient:false,lead:false};
export const conversationStatusLabels:Record<ConversationStatus,string>={new:"Nova",open:"Em atendimento",waiting_patient:"Aguardando paciente",waiting_team:"Aguardando equipe",resolved:"Resolvida",archived:"Arquivada"};
export const conversationPriorityLabels:Record<ConversationPriority,string>={low:"Baixa",normal:"Normal",high:"Alta",urgent:"Urgente"};
export const demoConversationTags=["Novo paciente","Orçamento","Retorno","Urgente","Sem resposta","Avaliação","Financeiro","Pós-atendimento","Lead quente","Reclamação"].map((name,i)=>({id:`tag-${i+1}`,name}));
export const quickReplies:QuickReply[]=[
 ["Confirmação de agendamento","Agenda","Olá! Seu agendamento na Clínica Aurora está confirmado."],["Lembrete","Agenda","Passando para lembrar seu atendimento. Podemos confirmar sua presença?"],["Envio de orçamento","Comercial","Seu orçamento demonstrativo está pronto. Posso esclarecer alguma condição?"],["Retorno","Relacionamento","Como você está? Gostaríamos de organizar seu retorno."],["Agradecimento","Relacionamento","Agradecemos seu contato e permanecemos à disposição."],["Informação de horário","Atendimento","Atendemos de segunda a sexta, das 8h às 18h."],["Solicitação de dados","Cadastro","Para localizar seu cadastro, poderia confirmar somente os dados necessários?"],["Pós-atendimento","Relacionamento","Como foi sua experiência após o atendimento?"],
].map((x,i)=>({id:`reply-${i+1}`,title:x[0]!,category:x[1]!,body:x[2]!}));
export const countUnreadConversations=(items:readonly Conversation[])=>items.reduce((s,c)=>s+c.unreadCount,0);
export const isConversationOverdue=(c:Conversation,now="2026-09-20T16:00:00.000Z")=>!["resolved","archived"].includes(c.status)&&new Date(now).getTime()-new Date(c.lastMessageAt).getTime()>(c.priority==="urgent"?30:120)*60000;
export function calculateConversationSla(c:Conversation,now="2026-09-20T16:00:00.000Z"){const last=Math.max(0,Math.floor((new Date(now).getTime()-new Date(c.lastMessageAt).getTime())/60000));const first=c.firstResponseAt&&c.messages[0]?Math.max(0,Math.floor((new Date(c.firstResponseAt).getTime()-new Date(c.messages[0].sentAt).getTime())/60000)):undefined;return{minutesSinceLastMessage:last,firstResponseMinutes:first,overdue:isConversationOverdue(c,now)}}
export function filterConversations(items:readonly Conversation[],f:ConversationFilters){const q=f.query.toLocaleLowerCase("pt-BR");return items.filter(c=>(!q||`${c.contactName} ${c.phone} ${c.email} ${c.messages.map(m=>m.body).join(" ")}`.toLocaleLowerCase("pt-BR").includes(q))&&(!f.channel||c.channel===f.channel)&&(!f.status||c.status===f.status)&&(!f.assignee||c.assignee===f.assignee)&&(!f.unit||c.unit===f.unit)&&(!f.priority||c.priority===f.priority)&&(!f.tag||c.tags.some(t=>t.name===f.tag))&&(!f.unread||c.unreadCount>0)&&(!f.overdue||isConversationOverdue(c))&&(!f.unassigned||!c.assignee)&&(!f.patient||!!c.patientId)&&(!f.lead||!!c.leadId)&&(f.archived||c.status!=="archived"))}
const priorityWeight:Record<ConversationPriority,number>={urgent:4,high:3,normal:2,low:1};
export function sortConversations(items:readonly Conversation[],key:"recent"|"priority"|"unread"="recent"){return [...items].sort((a,b)=>key==="priority"?priorityWeight[b.priority]-priorityWeight[a.priority]:key==="unread"?b.unreadCount-a.unreadCount:b.lastMessageAt.localeCompare(a.lastMessageAt))}
export const groupConversationsByStatus=(items:readonly Conversation[])=>Object.fromEntries((Object.keys(conversationStatusLabels) as ConversationStatus[]).map(s=>[s,items.filter(i=>i.status===s)])) as Record<ConversationStatus,Conversation[]>;
export function addConversationMessage(c:Conversation,body:string,type:MessageType="text",direction:ConversationMessage["direction"]="outgoing"){const sentAt="2026-09-20T16:05:00.000Z",message:ConversationMessage={id:`local-${c.messages.length+1}`,direction,type,body:body.trim(),sentAt,deliveryStatus:"sent",author:direction==="internal"?"Ana Souza":"Clínica Aurora"};return{...c,messages:[...c.messages,message],lastMessageAt:sentAt,status:(direction==="outgoing"?"waiting_patient":c.status) as ConversationStatus,unreadCount:0}}
export const assignConversation=(c:Conversation,assignee:string)=>({...c,assignee,messages:[...c.messages,{id:`event-${c.messages.length+1}`,direction:"internal" as const,type:"event" as const,body:assignee?`Conversa atribuída a ${assignee}.`:"Responsável removido.",sentAt:"2026-09-20T16:05:00.000Z",deliveryStatus:"read" as const,author:"Sistema"}]});
export const applyConversationTags=(c:Conversation,tags:ConversationTag[])=>({...c,tags:[...new Map([...c.tags,...tags].map(t=>[t.name,t])).values()]});
export const setConversationStatus=(c:Conversation,status:ConversationStatus)=>({...c,status,messages:[...c.messages,{id:`event-${c.messages.length+1}`,direction:"internal" as const,type:"event" as const,body:`Status alterado para ${conversationStatusLabels[status]}.`,sentAt:"2026-09-20T16:05:00.000Z",deliveryStatus:"read" as const,author:"Sistema"}]});
const contacts=["Marina Alves","João Pedro Lima","Beatriz Nunes","Renata Martins","Carlos Eduardo","Lívia Moreira","Paulo Reis","Sofia Mendes","André Castro","Nina Barros"],channels:ConversationChannel[]=["WhatsApp","Instagram","Messenger","Site","E-mail","Telefone","Interno"],statuses:ConversationStatus[]=["new","open","waiting_patient","waiting_team","resolved","archived"],priorities:ConversationPriority[]=["low","normal","high","urgent"],assignees=["Ana Souza","Bruno Melo","Carla Dias",""];
export const demoConversations:Conversation[]=Array.from({length:30},(_,i)=>{const at=`2026-09-${String(18+i%3).padStart(2,"0")}T${String(8+i%8).padStart(2,"0")}:00:00.000Z`;const incoming=i===1?"Vocês trabalham com implantes?": ["Gostaria de saber mais sobre o tratamento.","Posso confirmar meu horário?","Recebi o orçamento e tenho uma dúvida.","Preciso remarcar meu retorno."][i%4]!;return{id:`conv-${i+1}`,patientId:i%3!==1?`patient-${i%10+1}`:undefined,leadId:i%3===1?`lead-${i%10+1}`:undefined,treatmentPlanId:i%2===0?`plan-${i%25+1}`:undefined,appointmentId:i%4===0?`apt-${i%30+1}`:undefined,contactName:i<10?contacts[i]!: `Contato fictício ${i+1}`,phone:`+5586999****${String(20+i).slice(-2)}`,email:`contato${i+1}@exemplo.test`,channel:channels[i%7]!,status:statuses[i%6]!,priority:priorities[i%4]!,assignee:assignees[i%4]!,unit:i%3?"Centro":"Zona Leste",origin:["Instagram","Site","Indicação","Google"][i%4]!,tags:[demoConversationTags[i%10]!,...(i%4===0?[demoConversationTags[1]!]:[])],unreadCount:i%5,lastMessageAt:at,firstResponseAt:i%3?at:undefined,messages:[{id:`msg-${i}-1`,direction:"incoming",type:"text",body:incoming,sentAt:at,deliveryStatus:"read",author:contacts[i%10]!},...(i%3?[{id:`msg-${i}-2`,direction:"outgoing" as const,type:(["text","image","document","audio","location"] as MessageType[])[i%5]!,body:i%5===1?"Imagem simulada · orientações.png":i%5===2?"Documento simulado · orçamento.pdf":i%5===3?"Áudio simulado · 0:24":i%5===4?"Localização simulada · Clínica Aurora Centro":"Olá! Vou ajudar com seu atendimento.",sentAt:at,deliveryStatus:"delivered" as const,author:"Clínica Aurora"}]:[]),...(i%6===0?[{id:`note-${i}`,direction:"internal" as const,type:"internal_note" as const,body:"Nota interna: acompanhar retorno comercial.",sentAt:at,deliveryStatus:"read" as const,author:"Ana Souza",pinned:i%12===0}]:[])],lastVisitAt:"2026-08-14T12:00:00.000Z",nextAppointmentAt:i%4===0?"2026-09-24T14:00:00.000Z":undefined,potentialValueCents:80000+i*17000,consents:["Contato por canal demonstrativo"],notes:"Contato e dados inteiramente fictícios."}});
export type DemoMessage=ConversationMessage; export type DemoConversation=Conversation;
