export type LeadStage = "new"|"contacted"|"evaluation_scheduled"|"evaluation_done"|"proposal"|"negotiation"|"won"|"lost";
export type DemoLeadStage = LeadStage;
export type LeadTemperature = "cold"|"warm"|"hot";
export type LeadPriority = "low"|"medium"|"high"|"urgent";
export type LeadSource = "Instagram"|"Google"|"Indicação"|"Site"|"WhatsApp"|"Evento"|"Retorno"|"Ligação";
export interface LeadActivity { id:string; type:"created"|"contact"|"message"|"call"|"evaluation"|"proposal"|"stage"|"won"|"lost"|"note"; occurredAt:string; owner:string; summary:string; details:string }
export interface Lead { id:string; name:string; phone:string; email:string; source:LeadSource; stage:LeadStage; procedure:string; owner:string; unit:"Centro"|"Zona Leste"; estimatedValueCents:number; temperature:LeadTemperature; priority:LeadPriority; createdAt:string; stageChangedAt:string; lastInteractionAt:string; nextContactAt?:string|undefined; tags:string[]; notes:string; consent:boolean; patientId?:string|undefined; lostReason?:string|undefined; closedAt?:string|undefined; activities:LeadActivity[] }
export type DemoLead = Lead;
export interface LeadFilters { query:string; unit:string; owner:string; stage:string; source:string; procedure:string; temperature:string; priority:string; overdue:boolean; unassigned:boolean; minValueCents?:number; maxValueCents?:number }
export const emptyLeadFilters:LeadFilters={query:"",unit:"",owner:"",stage:"",source:"",procedure:"",temperature:"",priority:"",overdue:false,unassigned:false};
export const demoLeadStages:readonly {id:LeadStage;label:string}[]=[{id:"new",label:"Novo lead"},{id:"contacted",label:"Primeiro contato"},{id:"evaluation_scheduled",label:"Avaliação agendada"},{id:"evaluation_done",label:"Avaliação realizada"},{id:"proposal",label:"Proposta enviada"},{id:"negotiation",label:"Negociação"},{id:"won",label:"Fechado"},{id:"lost",label:"Perdido"}];
const names=["Ana Luiza Prado","Bruno Tavares","Carla Menezes","Daniel Ribeiro","Elaine Moura","Felipe Andrade","Gabriela Pires","Henrique Luz","Isabela Farias","José Matos","Karen Vieira","Leandro Gomes","Mônica Dias","Nicolas Ramos","Olívia Cunha","Pedro Sales","Queila Azevedo","Renato Freire","Sabrina Porto","Tiago Neves","Úrsula Leal","Vitor Dantas","Wesley Braga","Yara Monteiro","Alice Nascimento","Caio Peixoto","Débora Lopes","Eduardo Paiva","Flávia Reis","Gustavo Barros","Helena Campos","Igor Rocha","Júlia Martins","Kleber Sousa","Larissa Lima","Marcos Costa","Natália Melo","Otávio Nunes","Priscila Alves","Raul Moreira"];
const sources:LeadSource[]=["Instagram","Google","Indicação","Site","WhatsApp","Evento","Retorno","Ligação"];
const procedures=["Implante unitário","Clareamento","Alinhadores","Avaliação inicial","Facetas","Ortodontia"];
const owners=["Dra. Mariana Costa","Dr. Rafael Lima","Dra. Camila Rocha",""];
export const demoLeads:Lead[]=names.map((name,i)=>{const stage=demoLeadStages[i%8]!.id;const created=`2026-09-${String(1+i%15).padStart(2,"0")}T10:00:00.000Z`;return{id:`lead-${i+1}`,name,phone:`+5586999${String(1000000+i).slice(-7)}`,email:`contato${i+1}@exemplo.test`,source:sources[i%8]!,stage,procedure:procedures[i%6]!,owner:owners[i%4]!,unit:i%3?"Centro":"Zona Leste",estimatedValueCents:80000+(i%9)*95000,temperature:(['cold','warm','hot'] as LeadTemperature[])[i%3]!,priority:(['low','medium','high','urgent'] as LeadPriority[])[i%4]!,createdAt:created,stageChangedAt:created,lastInteractionAt:created,nextContactAt:i%5?`2026-09-${String(15+i%10).padStart(2,"0")}T14:00:00.000Z`:undefined,tags:[i%2?"Retorno rápido":"Campanha",procedures[i%6]!],notes:"Contato fictício para demonstração comercial.",consent:i%4!==0,activities:[{id:`activity-${i}`,type:"created",occurredAt:created,owner:owners[i%4]||"Equipe comercial",summary:"Lead criado",details:`Origem: ${sources[i%8]}.`} ]}});
export function isLeadOverdue(lead:Lead,now="2026-09-20T12:00:00.000Z"){return !!lead.nextContactAt&&lead.nextContactAt<now&&!(["won","lost"] as LeadStage[]).includes(lead.stage)}
export function filterLeads(leads:readonly Lead[],f:LeadFilters){const q=f.query.toLocaleLowerCase("pt-BR").replace(/\s/g,"");return leads.filter(l=>(!q||`${l.name}${l.phone}${l.procedure}`.toLocaleLowerCase("pt-BR").replace(/\s/g,"").includes(q))&&(!f.unit||l.unit===f.unit)&&(!f.owner||l.owner===f.owner)&&(!f.stage||l.stage===f.stage)&&(!f.source||l.source===f.source)&&(!f.procedure||l.procedure===f.procedure)&&(!f.temperature||l.temperature===f.temperature)&&(!f.priority||l.priority===f.priority)&&(!f.overdue||isLeadOverdue(l))&&(!f.unassigned||!l.owner)&&(!f.minValueCents||l.estimatedValueCents>=f.minValueCents)&&(!f.maxValueCents||l.estimatedValueCents<=f.maxValueCents))}
export function groupLeadsByStage(leads:readonly Lead[]){return Object.fromEntries(demoLeadStages.map(s=>[s.id,leads.filter(l=>l.stage===s.id)])) as Record<LeadStage,Lead[]>}
export const calculatePipelineValue=(leads:readonly Lead[])=>leads.filter(l=>l.stage!=="lost").reduce((s,l)=>s+l.estimatedValueCents,0);
export const calculateLeadConversion=(leads:readonly Lead[])=>leads.length?Math.round(leads.filter(l=>l.stage==="won").length/leads.length*100):0;
export function findDuplicateLead(leads:readonly Lead[],phone:string,email:string){const p=phone.replace(/\D/g,"");return leads.find(l=>l.phone.replace(/\D/g,"")===p||l.email.toLowerCase()===email.trim().toLowerCase())}
