import type { Lead } from "./leads";
export type PatientStatus="active"|"inactive"|"no_return"|"archived";
export interface PatientAddress{zip:string;street:string;number:string;complement:string;district:string;city:string;state:string}
export interface PatientTimelineEvent{id:string;type:"registration"|"appointment"|"confirmation"|"care"|"no_show"|"cancellation"|"estimate"|"payment"|"note"|"contact"|"consent";occurredAt:string;title:string;details:string;owner:string}
export interface PatientConsent{id:string;purpose:string;status:"granted"|"revoked";occurredAt:string;source:string}
export interface PatientNote{id:string;category:"clinical"|"administrative"|"commercial";content:string;pinned:boolean;createdAt:string}
export interface Patient{ id:string;name:string;socialName?:string|undefined;birthDate:string;phone:string;email:string;maskedCpf?:string|undefined;gender?:string|undefined;profession?:string|undefined;address:PatientAddress;professional:string;unit:"Centro"|"Zona Leste";source:string;status:PatientStatus;createdAt:string;lastVisitAt?:string|undefined;nextAppointmentAt?:string|undefined;lifetimeValueCents:number;visitCount:number;tags:string[];alerts:string[];accessibility:string;hasOpenEstimate:boolean;leadId?:string|undefined;timeline:PatientTimelineEvent[];consents:PatientConsent[];notes:PatientNote[] }
export type DemoPatient=Patient;
export interface PatientFilters{query:string;unit:string;professional:string;status:string;source:string;ageRange:string;birthday:boolean;openEstimate:boolean;noReturn:boolean;archived:boolean}
export const emptyPatientFilters:PatientFilters={query:"",unit:"",professional:"",status:"",source:"",ageRange:"",birthday:false,openEstimate:false,noReturn:false,archived:false};
const names=["Marina Alves","João Pedro Lima","Beatriz Nunes","Renata Martins","Carlos Eduardo","Lívia Moreira","Paulo Reis","Sofia Mendes","André Castro","Nina Barros","Amanda Freitas","Bernardo Silva","Cecília Moraes","Diego Santana","Elisa Cardoso","Fernando Lins","Giovana Torres","Hugo Cavalcante","Iara Fontes","Jonas Batista","Kelly Araújo","Luana Queiroz","Mateus Pinto","Nicole Correia","Orlando Sá","Paula Brito","Rogério Xavier","Sara Coelho","Tales Mendes","Vanessa Maia","William Dias","Zélia Ramos"];
const professionals=["Dra. Mariana Costa","Dr. Rafael Lima","Dra. Camila Rocha"];
export const demoPatients:Patient[]=names.map((name,i)=>({id:`patient-${i+1}`,name,birthDate:`${1970+i%35}-${String(1+i%12).padStart(2,"0")}-${String(2+i%25).padStart(2,"0")}`,phone:i===1?"+5586992223344":`+5586998${String(1000000+i).slice(-7)}`,email:`paciente${i+1}@exemplo.test`,maskedCpf:i%3?`***.***.***-${String(10+i).slice(-2)}`:undefined,address:{zip:"64***-***",street:"Rua fictícia",number:String(100+i),complement:"",district:"Centro",city:"Teresina",state:"PI"},professional:professionals[i%3]!,unit:i%3?"Centro":"Zona Leste",source:["Indicação","Instagram","Google","Retorno"][i%4]!,status:(['active','inactive','no_return','archived'] as PatientStatus[])[i%4]!,createdAt:`2026-0${1+i%8}-10T12:00:00.000Z`,lastVisitAt:i%5?`2026-08-${String(2+i%25).padStart(2,"0")}T12:00:00.000Z`:undefined,nextAppointmentAt:i%3?`2026-09-${String(20+i%8).padStart(2,"0")}T14:00:00.000Z`:undefined,lifetimeValueCents:120000+i*27000,visitCount:1+i%9,tags:[i%2?"Ortodontia":"Implante"],alerts:i%7===0?["Alergia fictícia sinalizada"]:[],accessibility:i%8===0?"Preferência por acesso sem degraus":"",hasOpenEstimate:i%3===0,leadId:i<8?`lead-${i+1}`:undefined,timeline:[{id:`pt-${i}`,type:"registration",occurredAt:`2026-0${1+i%8}-10T12:00:00.000Z`,title:"Paciente cadastrado",details:"Cadastro fictício criado na Clínica Aurora.",owner:"Equipe de recepção"}],consents:[{id:`consent-${i}`,purpose:"Tratamento de dados",status:"granted",occurredAt:"2026-01-10T12:00:00.000Z",source:"Cadastro demonstrativo"}],notes:[]}));
export function calculateAge(birthDate:string,today="2026-09-20"){const b=new Date(`${birthDate}T12:00:00Z`),t=new Date(`${today}T12:00:00Z`);let age=t.getUTCFullYear()-b.getUTCFullYear();if(t.getUTCMonth()<b.getUTCMonth()||(t.getUTCMonth()===b.getUTCMonth()&&t.getUTCDate()<b.getUTCDate()))age--;return age}
export const calculateTicketAverage=(p:Patient)=>p.visitCount?Math.round(p.lifetimeValueCents/p.visitCount):0;
export const calculateFrequency=(p:Patient)=>p.visitCount>1?Math.round(12/(p.visitCount-1)):0;
export const hasPendingReturn=(p:Patient)=>p.status==="no_return"||(!p.nextAppointmentAt&&p.status==="active");
export function filterPatients(items:readonly Patient[],f:PatientFilters){const q=f.query.toLowerCase().replace(/\s/g,"");return items.filter(p=>(!q||`${p.name}${p.phone}${p.email}`.toLowerCase().replace(/\s/g,"").includes(q))&&(!f.unit||p.unit===f.unit)&&(!f.professional||p.professional===f.professional)&&(!f.status||p.status===f.status)&&(!f.source||p.source===f.source)&&(!f.ageRange||(f.ageRange==="0-17"?calculateAge(p.birthDate)<18:f.ageRange==="18-39"?calculateAge(p.birthDate)<40&&calculateAge(p.birthDate)>=18:calculateAge(p.birthDate)>=40))&&(!f.birthday||p.birthDate.slice(5,7)==="09")&&(!f.openEstimate||p.hasOpenEstimate)&&(!f.noReturn||hasPendingReturn(p))&&((f.archived)||p.status!=="archived"))}
export function sortPatients(items:readonly Patient[],key:"name"|"lastVisitAt"|"lifetimeValueCents",direction:"asc"|"desc"="asc"){return [...items].sort((a,b)=>{const av=String(a[key]??""),bv=String(b[key]??"");const n=key==="lifetimeValueCents"?Number(a[key])-Number(b[key]):av.localeCompare(bv,"pt-BR");return direction==="asc"?n:-n})}
export function findDuplicatePatient(items:readonly Patient[],phone:string,email:string){const p=phone.replace(/\D/g,"");return items.find(x=>x.phone.replace(/\D/g,"")===p||x.email.toLowerCase()===email.trim().toLowerCase())}
export function convertLeadToPatient(lead:Lead,id=`patient-local-${Date.now()}`):Patient{return{id,name:lead.name,birthDate:"1990-01-01",phone:lead.phone,email:lead.email,address:{zip:"",street:"",number:"",complement:"",district:"",city:"",state:""},professional:lead.owner||"Dra. Mariana Costa",unit:lead.unit,source:lead.source,status:"active",createdAt:"2026-09-20T12:00:00.000Z",lifetimeValueCents:0,visitCount:0,tags:[lead.procedure],alerts:[],accessibility:"",hasOpenEstimate:false,leadId:lead.id,timeline:[{id:`conversion-${lead.id}`,type:"registration",occurredAt:"2026-09-20T12:00:00.000Z",title:"Convertido a partir do CRM",details:`Interesse em ${lead.procedure}.`,owner:lead.owner||"Equipe comercial"}],consents:[],notes:[]}}
