export interface ClinicSettings { name:string; tradeName:string; cnpj:string; phone:string; email:string; site:string; timezone:string; currency:string; language:string; defaultDuration:number; interval:number; logo:string; address:string; institutionalInfo:string }
export interface ClinicUnitSettings { id:string; name:string; slug:string; address:string; phone:string; hours:string; status:"active"|"inactive"; owner:string; rooms:number; professionalIds:string[] }
export interface ProfessionalSettings { id:string; name:string; specialty:string; registration:string; contact:string; unitIds:string[]; procedureIds:string[]; schedule:string; defaultDuration:number; color:string; status:"active"|"inactive"; commissionPercent:number }
export interface ProcedureSettings { id:string; name:string; category:string; description:string; duration:number; priceCents:number; costCents:number; professionalIds:string[]; unitIds:string[]; resource:string; interval:number; status:"active"|"inactive"; color:string; preparation:string; recommendedReturnDays:number }
export interface WorkingHours { day:number; enabled:boolean; startsAt:string; endsAt:string; breaks:{startsAt:string;endsAt:string}[] }
export type TeamMemberSettings = { id:string; name:string; email:string; role:"Proprietário"|"Gestor"|"Recepção"|"Profissional"|"Leitura"; status:"active"|"invited"|"suspended"; units:string[]; lastAccess:string; joinedAt:string };
export interface NotificationPreferences { event:string; email:boolean; push:boolean; whatsapp:boolean; internal:boolean }
export interface IntegrationSettings { id:string; name:string; status:"available"|"connected"|"disconnected"|"soon"; simulated:boolean }
export interface SecuritySettings { sessionTimeoutMinutes:number; passwordMinLength:number; requireNumbers:boolean; auditEnabled:boolean; twoFactorAvailable:boolean }
export interface BillingSettings { plan:string; priceCents:number; cycle:"monthly"|"annual"; nextDueDate:string; usage:{label:string;used:number;limit:number}[] }
export const initialClinicSettings:ClinicSettings={name:"Clínica Aurora Saúde Ltda.",tradeName:"Clínica Aurora",cnpj:"12.***.***/0001-**",phone:"+55 (86) 3214-0000",email:"contato@aurora.exemplo.test",site:"https://aurora.exemplo.test",timezone:"America/Fortaleza",currency:"BRL",language:"pt-BR",defaultDuration:45,interval:10,logo:"AU",address:"Av. Frei Serafim, 1200 · Centro · Teresina/PI",institutionalInfo:"Cuidado integrado em odontologia e saúde, com dados inteiramente fictícios."};
export const clinicUnitSettings:ClinicUnitSettings[]=[{id:"centro",name:"Centro",slug:"centro",address:"Av. Frei Serafim, 1200",phone:"+55 (86) 3214-0000",hours:"Seg–Sex · 08h–18h",status:"active",owner:"Ana Souza",rooms:5,professionalIds:["prof-ana","prof-caio","prof-livia"]},{id:"leste",name:"Zona Leste",slug:"zona-leste",address:"Av. João XXIII, 880",phone:"+55 (86) 3233-0000",hours:"Seg–Sex · 09h–19h",status:"active",owner:"Bruno Melo",rooms:3,professionalIds:["prof-ana","prof-livia"]}];
export const workingHours:WorkingHours[]=Array.from({length:7},(_,day)=>({day,enabled:day>0&&day<6,startsAt:"08:00",endsAt:"18:00",breaks:[{startsAt:"12:00",endsAt:"13:00"}]}));
export const teamMembers:TeamMemberSettings[]=[{id:"tm-1",name:"Ana Souza",email:"a***@aurora.exemplo.test",role:"Proprietário",status:"active",units:["Centro","Zona Leste"],lastAccess:"Hoje, 09:42",joinedAt:"2025-02-10"},{id:"tm-2",name:"Bruno Melo",email:"b***@aurora.exemplo.test",role:"Gestor",status:"active",units:["Centro"],lastAccess:"Ontem, 17:10",joinedAt:"2025-04-18"},{id:"tm-3",name:"Carla Dias",email:"c***@aurora.exemplo.test",role:"Recepção",status:"active",units:["Zona Leste"],lastAccess:"Hoje, 08:11",joinedAt:"2026-01-08"}];
export const integrations:IntegrationSettings[]=["WhatsApp","Instagram","Messenger","Google Calendar","Outlook","Asaas","Stripe","Google Analytics","Meta Ads","Google Ads","Webhooks","API"].map((name,i)=>({id:`int-${i}`,name,status:i===3?"connected":i>8?"soon":i%3===0?"available":"disconnected",simulated:true}));
export const validateClinic=(clinic:ClinicSettings)=>({name:clinic.name.trim()?"":"Informe o nome da clínica.",email:/^[^@]+@[^@]+\.[^@]+$/.test(clinic.email)?"":"Informe um e-mail válido.",timezone:clinic.timezone.includes("/")?"":"Informe um timezone IANA válido."});
export const detectWorkingHourOverlap=(ranges:{startsAt:string;endsAt:string}[])=>ranges.some((a,i)=>ranges.some((b,j)=>i!==j&&a.startsAt<b.endsAt&&b.startsAt<a.endsAt));
export const validateWorkingHours=(hours:WorkingHours[])=>hours.every(h=>!h.enabled||h.startsAt<h.endsAt&&!detectWorkingHourOverlap(h.breaks));
export const validateProcedure=(p:ProcedureSettings)=>p.name.trim().length>1&&Number.isInteger(p.priceCents)&&p.priceCents>=0&&p.duration>0;
export const calculatePlanUsage=(used:number,limit:number)=>limit?Math.min(100,Math.round(used/limit*100)):0;
export const hasUnsavedChanges=<T>(saved:T,current:T)=>JSON.stringify(saved)!==JSON.stringify(current);
