export type TreatmentPlanStatus="draft"|"review"|"sent"|"viewed"|"negotiation"|"accepted"|"partially_accepted"|"rejected"|"expired"|"cancelled";
export type TreatmentPlanItemStatus="pending"|"accepted"|"rejected";
export type PaymentMethod="pix"|"card"|"bank_slip"|"transfer"|"cash";
export interface TreatmentPlanItem{id:string;procedure:string;description:string;professional:string;unit:"Centro"|"Zona Leste";quantity:number;unitPriceCents:number;discountCents:number;durationMinutes:number;order:number;note:string;status:TreatmentPlanItemStatus}
export interface TreatmentPlanInstallment{id:string;number:number;dueDate:string;amountCents:number;status:"pending"|"paid"|"overdue";paymentMethod:PaymentMethod;paidAt?:string}
export interface TreatmentPlanActivity{id:string;type:string;occurredAt:string;title:string;details:string;owner:string}
export interface TreatmentPlan{id:string;number:string;patientId:string;patientName:string;leadId?:string|undefined;appointmentId?:string|undefined;title:string;professional:string;unit:"Centro"|"Zona Leste";owner:string;origin:string;items:TreatmentPlanItem[];generalDiscountCents:number;entryCents:number;installmentCount:number;paymentMethod:PaymentMethod;installments:TreatmentPlanInstallment[];status:TreatmentPlanStatus;createdAt:string;updatedAt:string;expiresAt:string;nextAction:string;notes:string;activities:TreatmentPlanActivity[];duplicatedFrom?:string|undefined}
export interface TreatmentPlanFilters{query:string;status:string;unit:string;professional:string;owner:string;patient:string;procedure:string;origin:string;minValueCents?:number;maxValueCents?:number;expiringSoon:boolean;withDiscount:boolean;withoutReturn:boolean;partial:boolean}
export const emptyTreatmentPlanFilters:TreatmentPlanFilters={query:"",status:"",unit:"",professional:"",owner:"",patient:"",procedure:"",origin:"",expiringSoon:false,withDiscount:false,withoutReturn:false,partial:false};
export const treatmentPlanStatusLabels:Record<TreatmentPlanStatus,string>={draft:"Rascunho",review:"Em revisão",sent:"Enviado",viewed:"Visualizado",negotiation:"Em negociação",accepted:"Aceito",partially_accepted:"Parcialmente aceito",rejected:"Rejeitado",expired:"Expirado",cancelled:"Cancelado"};
export const paymentMethodLabels:Record<PaymentMethod,string>={pix:"PIX",card:"Cartão",bank_slip:"Boleto",transfer:"Transferência",cash:"Dinheiro"};
export const procedureCatalog=[
 ["Avaliação",18000,45],["Limpeza",26000,45],["Clareamento",120000,60],["Implante",380000,90],["Harmonização facial",210000,75],["Consulta dermatológica",30000,45],["Retorno",0,30],["Procedimento estético",165000,60],["Faceta em resina",85000,60],["Alinhadores",490000,60],["Ortodontia",24000,30],["Restauração",42000,45],["Prótese",320000,90],["Preenchimento",145000,60],["Profilaxia",22000,40],
] as const;
export const roundMoney=(value:number)=>Math.round(value);
export const calculateItemTotal=(i:TreatmentPlanItem)=>Math.max(0,i.quantity*i.unitPriceCents-i.discountCents);
export const calculateSubtotal=(items:readonly TreatmentPlanItem[])=>items.reduce((s,i)=>s+i.quantity*i.unitPriceCents,0);
export const calculateItemDiscounts=(items:readonly TreatmentPlanItem[])=>items.reduce((s,i)=>s+i.discountCents,0);
export const calculateTotal=(items:readonly TreatmentPlanItem[],generalDiscountCents=0)=>Math.max(0,calculateSubtotal(items)-calculateItemDiscounts(items)-generalDiscountCents);
export const calculateBalance=(plan:TreatmentPlan)=>Math.max(0,calculateTotal(plan.items,plan.generalDiscountCents)-plan.entryCents);
export function calculateInstallments(balanceCents:number,count:number,firstDue="2026-10-10",intervalDays=30,method:PaymentMethod="pix"){const safe=Math.max(1,count),base=Math.floor(balanceCents/safe),remainder=balanceCents-base*safe;return Array.from({length:safe},(_,i)=>{const date=new Date(`${firstDue}T12:00:00Z`);date.setUTCDate(date.getUTCDate()+i*intervalDays);return{id:`installment-${i+1}`,number:i+1,dueDate:date.toISOString().slice(0,10),amountCents:base+(i<remainder?1:0),status:"pending" as const,paymentMethod:method}})}
export const calculateAcceptedValue=(p:TreatmentPlan)=>p.items.filter(i=>i.status==="accepted").reduce((s,i)=>s+calculateItemTotal(i),0);
export const calculatePendingValue=(p:TreatmentPlan)=>Math.max(0,calculateTotal(p.items,p.generalDiscountCents)-calculateAcceptedValue(p));
export const calculateDemoMargin=(p:TreatmentPlan)=>Math.round(calculateTotal(p.items,p.generalDiscountCents)*0.42);
export const daysUntilExpiration=(date:string,now="2026-09-20T12:00:00.000Z")=>Math.ceil((new Date(date).getTime()-new Date(now).getTime())/86400000);
export const isTreatmentPlanExpired=(p:TreatmentPlan,now="2026-09-20T12:00:00.000Z")=>daysUntilExpiration(p.expiresAt,now)<0&&!(["accepted","rejected","cancelled"] as TreatmentPlanStatus[]).includes(p.status);
const transitions:Record<TreatmentPlanStatus,TreatmentPlanStatus[]>={draft:["review","cancelled"],review:["draft","sent","cancelled"],sent:["viewed","cancelled"],viewed:["negotiation","accepted","rejected","cancelled"],negotiation:["accepted","partially_accepted","rejected","cancelled"],partially_accepted:["accepted","rejected","cancelled"],accepted:["cancelled"],rejected:["cancelled"],expired:["cancelled"],cancelled:[]};
export const canTransitionTreatmentPlan=(from:TreatmentPlanStatus,to:TreatmentPlanStatus)=>transitions[from].includes(to);
export function transitionTreatmentPlan(p:TreatmentPlan,status:TreatmentPlanStatus,owner=p.owner){if(!canTransitionTreatmentPlan(p.status,status))return p;return{...p,status,updatedAt:"2026-09-20T16:00:00.000Z",activities:[...p.activities,{id:`activity-${p.activities.length+1}`,type:"status",occurredAt:"2026-09-20T16:00:00.000Z",title:`Status alterado para ${treatmentPlanStatusLabels[status]}`,details:"Alteração demonstrativa em estado local.",owner}]}}
export function duplicateTreatmentPlan(p:TreatmentPlan,index=99):TreatmentPlan{const created="2026-09-20T16:00:00.000Z";return{...p,id:`plan-local-${index}`,number:`ORC-2026-${String(index).padStart(4,"0")}`,status:"draft",createdAt:created,updatedAt:created,expiresAt:"2026-10-20T23:59:59.000Z",duplicatedFrom:p.id,items:p.items.map(i=>({...i,id:`${i.id}-copy`,status:"pending"})),activities:[{id:"activity-1",type:"created",occurredAt:created,title:"Orçamento duplicado",details:`Criado a partir de ${p.number}.`,owner:p.owner}]}}
export function acceptTreatmentPlanItems(p:TreatmentPlan,itemIds:readonly string[]){const items=p.items.map(i=>itemIds.includes(i.id)&&i.status==="pending"?{...i,status:"accepted" as const}:i);const all=items.every(i=>i.status==="accepted");return{...p,items,status:(all?"accepted":"partially_accepted") as TreatmentPlanStatus,updatedAt:"2026-09-20T16:00:00.000Z",activities:[...p.activities,{id:`activity-${p.activities.length+1}`,type:"item_accepted",occurredAt:"2026-09-20T16:00:00.000Z",title:all?"Orçamento aceito":"Aceite parcial registrado",details:`${itemIds.length} item(ns) selecionado(s).`,owner:p.owner}]}}
export function filterTreatmentPlans(items:readonly TreatmentPlan[],f:TreatmentPlanFilters){const q=f.query.toLocaleLowerCase("pt-BR");return items.filter(p=>{const total=calculateTotal(p.items,p.generalDiscountCents);return(!q||`${p.number} ${p.patientName} ${p.items.map(i=>i.procedure).join(" ")}`.toLocaleLowerCase("pt-BR").includes(q))&&(!f.status||p.status===f.status)&&(!f.unit||p.unit===f.unit)&&(!f.professional||p.professional===f.professional)&&(!f.owner||p.owner===f.owner)&&(!f.patient||p.patientId===f.patient)&&(!f.procedure||p.items.some(i=>i.procedure===f.procedure))&&(!f.origin||p.origin===f.origin)&&(f.minValueCents===undefined||total>=f.minValueCents)&&(f.maxValueCents===undefined||total<=f.maxValueCents)&&(!f.expiringSoon||(daysUntilExpiration(p.expiresAt)>=0&&daysUntilExpiration(p.expiresAt)<=7))&&(!f.withDiscount||calculateItemDiscounts(p.items)+p.generalDiscountCents>0)&&(!f.withoutReturn||p.nextAction.includes("retorno"))&&(!f.partial||p.status==="partially_accepted")})}
export function sortTreatmentPlans(items:readonly TreatmentPlan[],key:"updatedAt"|"total"|"expiresAt"|"patientName",direction:"asc"|"desc"="desc"){return [...items].sort((a,b)=>{const n=key==="total"?calculateTotal(a.items,a.generalDiscountCents)-calculateTotal(b.items,b.generalDiscountCents):String(a[key]).localeCompare(String(b[key]),"pt-BR");return direction==="asc"?n:-n})}
export const calculateTreatmentPlanConversion=(p:readonly TreatmentPlan[])=>p.length?Math.round(p.filter(x=>["accepted","partially_accepted"].includes(x.status)).length/p.length*100):0;
export const calculateTreatmentPlanAverageTicket=(p:readonly TreatmentPlan[])=>{const won=p.filter(x=>["accepted","partially_accepted"].includes(x.status));return won.length?Math.round(won.reduce((s,x)=>s+calculateTotal(x.items,x.generalDiscountCents),0)/won.length):0};
const professionals=["Dra. Mariana Costa","Dr. Rafael Lima","Dra. Camila Rocha"],owners=["Ana Souza","Bruno Melo","Carla Dias"],statuses=Object.keys(treatmentPlanStatusLabels) as TreatmentPlanStatus[];
export const demoTreatmentPlans:TreatmentPlan[]=Array.from({length:25},(_,i)=>{const patientNames=["Marina Alves","João Pedro Lima","Beatriz Nunes","Renata Martins","Carlos Eduardo","Lívia Moreira","Paulo Reis","Sofia Mendes","André Castro","Nina Barros"];const proc=procedureCatalog[i%procedureCatalog.length]!,second=procedureCatalog[(i+2)%procedureCatalog.length]!;const items:[TreatmentPlanItem,...TreatmentPlanItem[]]=[{id:`item-${i}-1`,procedure:proc[0],description:`Etapa de ${proc[0].toLocaleLowerCase("pt-BR")}`,professional:professionals[i%3]!,unit:i%3?"Centro":"Zona Leste",quantity:1+i%2,unitPriceCents:proc[1],discountCents:i%4===0?5000:0,durationMinutes:proc[2],order:1,note:"Orientações explicadas durante a avaliação.",status:i%10===5?"accepted":"pending"},{id:`item-${i}-2`,procedure:second[0],description:`Complemento: ${second[0]}`,professional:professionals[i%3]!,unit:i%3?"Centro":"Zona Leste",quantity:1,unitPriceCents:second[1],discountCents:0,durationMinutes:second[2],order:2,note:"",status:"pending"}];const created=`2026-09-${String(1+i%18).padStart(2,"0")}T12:00:00.000Z`,expires=`2026-${i%9===0?"09":"10"}-${String(12+i%18).padStart(2,"0")}T23:59:59.000Z`,total=calculateTotal(items,i%5===0?10000:0),entry=Math.min(50000,total);return{id:`plan-${i+1}`,number:`ORC-2026-${String(i+1).padStart(4,"0")}`,patientId:`patient-${i%10+1}`,patientName:patientNames[i%10]!,leadId:i<8?`lead-${i+1}`:undefined,appointmentId:i<10?`apt-${i+1}`:undefined,title:`Plano de ${proc[0]}`,professional:professionals[i%3]!,unit:i%3?"Centro":"Zona Leste",owner:owners[i%3]!,origin:["CRM","Inbox","Indicação","Agenda"][i%4]!,items,generalDiscountCents:i%5===0?10000:0,entryCents:entry,installmentCount:1+i%6,paymentMethod:(["pix","card","bank_slip","transfer","cash"] as PaymentMethod[])[i%5]!,installments:calculateInstallments(Math.max(0,total-entry),1+i%6,"2026-10-10",30,(["pix","card","bank_slip","transfer","cash"] as PaymentMethod[])[i%5]!),status:statuses[i%statuses.length]!,createdAt:created,updatedAt:created,expiresAt:expires,nextAction:i%4===0?"Aguardar retorno":"Revisar proposta",notes:"Condições demonstrativas válidas durante o período indicado.",activities:[{id:`activity-${i}`,type:"created",occurredAt:created,title:"Orçamento criado",details:"Plano criado na Clínica Aurora.",owner:owners[i%3]!}]}});
demoTreatmentPlans[0]={...demoTreatmentPlans[0]!,status:"sent",items:[{...demoTreatmentPlans[0]!.items[0]!,procedure:"Clareamento",description:"Clareamento",quantity:1,unitPriceCents:120000,discountCents:0},{...demoTreatmentPlans[0]!.items[1]!,procedure:"Faceta em resina",description:"Faceta em resina",quantity:4,unitPriceCents:85000,discountCents:0}],generalDiscountCents:0};
demoTreatmentPlans[1]={...demoTreatmentPlans[1]!,status:"accepted",items:demoTreatmentPlans[1]!.items.map(i=>({...i,status:"accepted"}))};
export type DemoPlanStatus=TreatmentPlanStatus; export type DemoPlanItem=TreatmentPlanItem; export type DemoTreatmentPlan=TreatmentPlan;
export const demoPlanStatusLabels=treatmentPlanStatusLabels;
