import type { AppointmentReader, ClinicReader, ListQuery, ProfessionalReader, ProcedureReader, ResourceReader, WorkingHoursReader } from "@/domains/application/readers";
import { normalizePage, parseDateRange, type DateRange } from "@/domains/application/query";
import type { AppointmentStatus, ClinicSummary } from "@/domains/application/view-models";
import { clinicUnits, demoAppointments, scheduleProcedures, scheduleProfessionals } from "@/domains/demo/appointments";

function paginate<T>(all: T[], request = {}) { const { offset, limit } = normalizePage(request); const items = all.slice(offset, offset + limit); return { items, page: { offset, limit, total: all.length, hasMore: offset + items.length < all.length } }; }
const clinics: ClinicSummary[] = clinicUnits.map((item) => ({ id: item.id, name: item.name, slug: item.id, timezone: "America/Sao_Paulo", active: true }));
const professionals = scheduleProfessionals.map((item) => ({ id: item.id, name: item.name, specialty: item.specialty, registration: null, color: item.color, active: true, clinics: clinics.filter((clinic) => item.unitIds.includes(clinic.id)) }));
const procedures = scheduleProcedures.map((item) => ({ id: item.id, name: item.name, category: null, durationMinutes: item.durationMinutes, priceCents: item.priceCents, active: true, professionals: professionals.map(({ id, name }) => ({ id, name })) }));
const resources = [...new Set(demoAppointments.map((item) => `${item.unitId}|${item.resource}`))].map((key, index) => { const [clinicId, name] = key.split("|") as [string, string]; return { id: `resource-${index + 1}`, clinicId, clinicName: clinics.find((c) => c.id === clinicId)?.name ?? "Unidade", name, kind: "room" as const, active: true }; });
const statusMap: Record<string, AppointmentStatus> = { scheduled: "scheduled", confirmed: "confirmed", waiting: "arrived", in_service: "arrived", completed: "attended", no_show: "no_show", cancelled: "cancelled" };
const appointments = demoAppointments.map((item) => { const professional = professionals.find((p) => p.id === item.professionalId)!; const procedure = procedures.find((p) => p.id === item.procedureId)!; const clinic = clinics.find((c) => c.id === item.unitId)!; const resource = resources.find((r) => r.clinicId === item.unitId && r.name === item.resource)!; return { id: item.id, clinicId: clinic.id, clinicName: clinic.name, professionalId: professional.id, professionalName: professional.name, patientId: `demo-patient-${item.id}`, patientName: item.patientName, procedureId: procedure.id, procedureName: procedure.name, resourceId: resource.id, resourceName: resource.name, startsAt: new Date(item.startsAt).toISOString(), endsAt: new Date(new Date(item.startsAt).getTime() + item.durationMinutes * 60_000).toISOString(), status: statusMap[item.status]!, priceCents: item.revenueCents, cancellationReason: null, source: item.origin }; });

export class DemoClinicReader implements ClinicReader { async list(q: ListQuery = {}) { return paginate(clinics, q); } async findById(id: string) { return clinics.find((x) => x.id === id) ?? null; } }
export class DemoProfessionalReader implements ProfessionalReader { async list(q: ListQuery & { clinicId?: string } = {}) { return paginate(professionals.filter((x) => !q.clinicId || x.clinics.some((c) => c.id === q.clinicId)), q); } async findById(id: string) { return professionals.find((x) => x.id === id) ?? null; } }
export class DemoProcedureReader implements ProcedureReader { async list(q: ListQuery & { active?: boolean } = {}) { return paginate(procedures.filter((x) => q.active === undefined || x.active === q.active), q); } async findById(id: string) { return procedures.find((x) => x.id === id) ?? null; } }
export class DemoResourceReader implements ResourceReader { async list(q: ListQuery & { clinicId?: string } = {}) { return paginate(resources.filter((x) => !q.clinicId || x.clinicId === q.clinicId), q); } async findById(id: string) { return resources.find((x) => x.id === id) ?? null; } }
export class DemoWorkingHoursReader implements WorkingHoursReader { async list(q: ListQuery & { professionalId?: string; clinicId?: string; range?: DateRange }) { const values = professionals.flatMap((professional) => professional.clinics.flatMap((clinic) => [1, 2, 3, 4, 5].map((weekday) => ({ id: `${professional.id}-${clinic.id}-${weekday}`, professionalId: professional.id, clinicId: clinic.id, weekday, startMinute: 480, endMinute: 1080, validFrom: null, validUntil: null, active: true })))).filter((x) => (!q.professionalId || x.professionalId === q.professionalId) && (!q.clinicId || x.clinicId === q.clinicId)); return paginate(values, q); } }
export class DemoAppointmentReader implements AppointmentReader { async list(q: ListQuery & { range: DateRange; clinicId?: string; professionalId?: string; status?: AppointmentStatus }) { const range = parseDateRange(q.range); return paginate(appointments.filter((x) => new Date(x.startsAt) >= range.from && new Date(x.startsAt) < range.to && (!q.clinicId || x.clinicId === q.clinicId) && (!q.professionalId || x.professionalId === q.professionalId) && (!q.status || x.status === q.status)), q); } async findById(id: string) { return appointments.find((x) => x.id === id) ?? null; } }

