"use client";
import { Search,UserRound } from "lucide-react";
import { useMemo,useState } from "react";
import { demoPatients } from "@/domains/demo";
import { formatCompactCurrency } from "@/lib/formatting/currency";
import { formatDate } from "@/lib/formatting/date";
import { formatPhone } from "@/lib/formatting/phone";
import { EmptyState } from "@/components/shared/empty-state";
import { PageHeader } from "@/components/shared/page-header";
export function PatientsView(){const [query,setQuery]=useState("");const patients=useMemo(()=>{const normalized=query.toLocaleLowerCase("pt-BR").replace(/\D/g,"");return demoPatients.filter(p=>p.name.toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR"))|| (!!normalized&&p.phone.replace(/\D/g,"").includes(normalized)))},[query]);return <div className="mx-auto max-w-6xl space-y-7"><PageHeader eyebrow="Cadastros · Relacionamento" title="Pacientes" description="Busca local sobre uma lista inteiramente fictícia; nenhum dado é enviado ou persistido."/><label className="flex max-w-md items-center gap-2 rounded-md border border-line bg-bg-elev px-3"><Search aria-hidden="true" size={16} className="text-ink-dim"/><span className="sr-only">Buscar pacientes por nome ou telefone</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por nome ou telefone" className="h-11 flex-1 bg-transparent text-sm outline-none"/></label>{patients.length?<div className="overflow-x-auto rounded-lg border border-line"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-bg-elev font-mono text-[10px] uppercase tracking-wider text-ink-dim"><tr><th className="p-4">Paciente</th><th>Telefone</th><th>Tags</th><th>LTV</th><th>Última visita</th></tr></thead><tbody className="divide-y divide-line bg-bg-alt">{patients.map(p=><tr key={p.id}><td className="p-4 font-medium">{p.name}</td><td className="font-mono text-xs">{formatPhone(p.phone)}</td><td><div className="flex gap-1">{p.tags.map(t=><span key={t} className="rounded-full border border-line px-2 py-1 text-[10px]">{t}</span>)}</div></td><td className="font-display text-xl">{formatCompactCurrency(p.lifetimeValueCents)}</td><td className="text-ink-muted">{formatDate(p.lastVisitAt)}</td></tr>)}</tbody></table></div>:<div className="card-surface"><EmptyState icon={UserRound} title="Nenhum paciente encontrado" description="Ajuste a busca para consultar os dados fictícios disponíveis."/></div>}</div>}
