import "server-only";
import type { Prisma,PrismaClient,SubscriptionStatus,PaymentStatus } from "@/generated/prisma/client";
import type { BillingProviderAdapter,ProviderPayment } from "@/domains/application/billing";
import { ProviderPermanentError } from "@/domains/application/integrations";
const subscriptions:Readonly<Record<string,SubscriptionStatus>>={ACTIVE:"ACTIVE",PENDING:"PENDING",OVERDUE:"PAST_DUE",INACTIVE:"SUSPENDED",EXPIRED:"EXPIRED",DELETED:"CANCELLED"};
const payments:Readonly<Record<string,PaymentStatus>>={PENDING:"PENDING",CONFIRMED:"CONFIRMED",RECEIVED:"RECEIVED",OVERDUE:"OVERDUE",REFUNDED:"REFUNDED",DELETED:"CANCELLED",CANCELLED:"CANCELLED",CREDIT_CARD_CAPTURE_REFUSED:"FAILED"};
export const mapAsaasSubscriptionStatus=(value:string)=>subscriptions[value]??null;
export const mapAsaasPaymentStatus=(value:string)=>payments[value]??null;
export class AsaasBillingReconciliationService {
 constructor(private prisma:PrismaClient,private adapter:BillingProviderAdapter){}
 async reconcile(tenantId:string,subscriptionId:string,correlationId:string){
  const local=await this.prisma.subscription.findFirst({where:{id:subscriptionId,tenantId,provider:"ASAAS"},select:{id:true,externalSubscriptionId:true,currentPeriodStart:true,currentPeriodEnd:true}});if(!local?.externalSubscriptionId)throw new Error("RECONCILIATION_REQUIRED");
  const result=await this.adapter.reconcileSubscription(local.externalSubscriptionId,correlationId),status=mapAsaasSubscriptionStatus(result.subscription.status);if(!status){await this.prisma.subscription.updateMany({where:{id:local.id,tenantId},data:{providerStatus:result.subscription.status,lastSyncedAt:new Date()}});throw new ProviderPermanentError("UNKNOWN_SUBSCRIPTION_STATUS")}
  for(const item of result.payments)if(!mapAsaasPaymentStatus(item.status))throw new ProviderPermanentError("UNKNOWN_PAYMENT_STATUS");
  const now=new Date();await this.prisma.$transaction(async tx=>{await tx.subscription.updateMany({where:{id:local.id,tenantId},data:{providerStatus:result.subscription.status,status,...(result.subscription.customerId?{externalCustomerId:result.subscription.customerId}:{}),lastSyncedAt:now}});for(const item of result.payments)await this.upsertPayment(tx,tenantId,local.id,item,correlationId,now);if(result.payments.some(x=>["CONFIRMED","RECEIVED"].includes(mapAsaasPaymentStatus(x.status)??"")))await this.activatePaid(tx,tenantId,local.id,local.currentPeriodStart??now,local.currentPeriodEnd);await tx.auditLog.create({data:{tenantId,action:"platform.billing.reconciled",resourceType:"Subscription",resourceId:local.id,outcome:"SUCCESS",correlationId}})});return {payments:result.payments.length};
 }
 private upsertPayment(prisma:Prisma.TransactionClient,tenantId:string,subscriptionId:string,item:ProviderPayment,correlationId:string,now:Date){const status=mapAsaasPaymentStatus(item.status);if(!status)throw new ProviderPermanentError("UNKNOWN_PAYMENT_STATUS");return prisma.payment.upsert({where:{tenantId_provider_externalPaymentId:{tenantId,provider:"ASAAS",externalPaymentId:item.id}},create:{tenantId,subscriptionId,provider:"ASAAS",externalPaymentId:item.id,status,providerStatus:item.status,amountCents:item.valueCents,dueAt:new Date(`${item.dueDate}T12:00:00Z`),paidAt:item.paymentDate?new Date(`${item.paymentDate}T12:00:00Z`):null,lastSyncedAt:now,correlationId},update:{status,providerStatus:item.status,amountCents:item.valueCents,paidAt:item.paymentDate?new Date(`${item.paymentDate}T12:00:00Z`):null,lastSyncedAt:now,correlationId}})}
 private async activatePaid(tx:Prisma.TransactionClient,tenantId:string,subscriptionId:string,startsAt:Date,endsAt:Date|null){if(await tx.accessEntitlement.findFirst({where:{tenantId,type:{in:["COURTESY","INTERNAL"]},status:"ACTIVE"},select:{id:true}}))return;const current=await tx.accessEntitlement.findFirst({where:{tenantId,type:"PAID",status:"ACTIVE"},orderBy:{createdAt:"desc"}});if(current)await tx.accessEntitlement.update({where:{id:current.id},data:{startsAt,endsAt,reason:`SaaS subscription ${subscriptionId}`}});else await tx.accessEntitlement.create({data:{tenantId,type:"PAID",status:"ACTIVE",startsAt,endsAt,reason:`SaaS subscription ${subscriptionId}`}})}
}
