import type { AppointmentSummary, ClinicSummary, ProcedureSummary, ProfessionalSummary, ResourceSummary } from "@/domains/application";
import { createAppointment, rescheduleAppointment, transitionAppointment } from "@/app/(platform)/[tenantSlug]/operational-actions";
import { StatusBadge } from "@/components/shared/status-badge";

async function createForm(form: FormData) { "use server"; await createAppointment(form); }
async function transitionForm(form: FormData) { "use server"; await transitionAppointment(form); }
async function rescheduleForm(form: FormData) { "use server"; await rescheduleAppointment(form); }

const input="rounded-md border border-line bg-bg-elev p-2 text-sm";
export function RealAgendaView({tenantSlug,timezone,appointments,clinics,professionals,procedures,resources}:{tenantSlug:string;timezone:string;appointments:AppointmentSummary[];clinics:ClinicSummary[];professionals:ProfessionalSummary[];procedures:ProcedureSummary[];resources:ResourceSummary[]}) {
 return <div className="mx-auto max-w-7xl space-y-6"><header><p className="font-mono text-xs uppercase tracking-wider text-primary">Operação real · {timezone}</p><h1 className="font-display text-5xl">Agenda</h1><p className="text-sm text-ink-muted">Horários exibidos no fuso do tenant. Alterações são validadas e auditadas no servidor.</p></header>
 <details className="card-surface p-5"><summary className="cursor-pointer font-medium">Novo agendamento</summary><form action={createForm} className="mt-4 grid gap-3 md:grid-cols-3"><input type="hidden" name="tenantSlug" value={tenantSlug}/><select required name="clinicId" className={input}><option value="">Unidade</option>{clinics.filter(x=>x.active).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select required name="professionalId" className={input}><option value="">Profissional</option>{professionals.filter(x=>x.active).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input required name="patientId" placeholder="ID do paciente" className={input}/><select name="procedureId" className={input}><option value="">Procedimento</option>{procedures.filter(x=>x.active).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="resourceId" className={input}><option value="">Sem recurso</option>{resources.filter(x=>x.active).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input name="source" placeholder="Origem" className={input}/><label className="text-xs">Início UTC<input required type="datetime-local" name="startsAt" className={`block w-full ${input}`}/></label><label className="text-xs">Fim UTC<input required type="datetime-local" name="endsAt" className={`block w-full ${input}`}/></label><input type="number" min="0" name="priceCents" placeholder="Valor em centavos" className={input}/><button className="rounded-md bg-primary p-2 text-primary-foreground">Salvar agendamento</button></form></details>
 {!appointments.length?<div className="card-surface p-12 text-center"><h2 className="font-display text-2xl">Nenhum agendamento no período</h2><p className="text-sm text-ink-muted">Crie o primeiro agendamento ou navegue para outro período.</p></div>:<div className="space-y-3">{appointments.map(a=><article className="card-surface p-4" key={a.id}><div className="flex flex-wrap justify-between gap-3"><div><strong>{a.patientName}</strong><p className="text-sm text-ink-muted">{new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short",timeZone:timezone}).format(new Date(a.startsAt))} · {a.professionalName} · {a.clinicName}</p><p className="text-xs">{a.procedureName??"Sem procedimento"} · {a.resourceName??"Sem recurso"}</p></div><StatusBadge>{a.status}</StatusBadge></div><div className="mt-3 flex flex-wrap gap-2">{([...["confirmed","arrived","attended","no_show","cancelled"]] as const).map(status=><form action={transitionForm} key={status}><input type="hidden" name="tenantSlug" value={tenantSlug}/><input type="hidden" name="id" value={a.id}/><input type="hidden" name="status" value={status}/><button className="rounded border border-line px-2 py-1 text-xs">{({confirmed:"Confirmar",arrived:"Marcar chegada",attended:"Finalizar",no_show:"Marcar falta",cancelled:"Cancelar"} as const)[status]}</button></form>)}<details><summary className="cursor-pointer text-xs text-primary">Reagendar</summary><form action={rescheduleForm} className="mt-2 flex gap-2"><input type="hidden" name="tenantSlug" value={tenantSlug}/><input type="hidden" name="id" value={a.id}/><input required type="datetime-local" name="startsAt" className={input}/><input required type="datetime-local" name="endsAt" className={input}/><button className="text-xs text-primary">Confirmar</button></form></details></div></article>)}</div>}</div>;
}
