"use client";
import { Bell, ChevronDown, CircleHelp } from "lucide-react";
import { usePathname } from "next/navigation";
import { useState } from "react";
import { Avatar } from "@/components/shared/avatar";
import { DemoBadge } from "@/components/shared/demo-badge";
import { SearchInput } from "@/components/shared/search-input";
import { DemoMobileDrawer } from "@/components/app-shell/demo-mobile-drawer";
import { demoPageDescriptions } from "@/lib/demo/navigation";

export function DemoTopbar() { const pathname = usePathname(); const [menu, setMenu] = useState(false); const title = demoPageDescriptions[pathname] ?? "Demonstração"; return <header className="sticky top-0 z-30 flex min-h-16 items-center gap-3 border-b border-line bg-bg/90 px-3 backdrop-blur md:px-6"><DemoMobileDrawer /><div className="min-w-0 flex-1"><nav aria-label="Breadcrumb" className="hidden text-[11px] text-ink-dim sm:block"><ol className="flex items-center gap-2"><li>Clínica Aurora</li><li aria-hidden="true">/</li><li aria-current="page" className="text-ink-muted">{title}</li></ol></nav><p className="truncate text-sm font-medium sm:mt-1">{title}</p></div><div className="hidden w-64 xl:block"><SearchInput /></div><div className="hidden md:block"><DemoBadge /></div><button type="button" aria-label="Central de ajuda" className="hidden h-10 w-10 items-center justify-center rounded-md text-ink-muted hover:bg-bg-hover sm:flex"><CircleHelp aria-hidden="true" size={18} /></button><button type="button" aria-label="Notificações, 3 não lidas" className="relative flex h-10 w-10 items-center justify-center rounded-md text-ink-muted hover:bg-bg-hover"><Bell aria-hidden="true" size={18} /><span className="absolute right-2 top-2 h-2 w-2 rounded-full bg-danger" /></button><div className="relative"><button type="button" aria-label="Abrir menu do usuário" aria-expanded={menu} onClick={() => setMenu((value) => !value)} className="flex min-h-11 items-center gap-2 rounded-md px-1 hover:bg-bg-hover"><Avatar name="Mariana Costa" size="sm" /><span className="hidden text-left xl:block"><span className="block text-xs font-medium">Mariana Costa</span><span className="block text-[10px] text-ink-dim">Gestora</span></span><ChevronDown aria-hidden="true" size={13} className="hidden text-ink-dim sm:block" /></button>{menu ? <div role="menu" className="absolute right-0 top-full mt-2 w-52 rounded-md border border-line bg-bg-alt p-2 shadow-subtle"><p className="px-2 py-2 text-xs text-ink-muted">Ambiente somente visual</p><button role="menuitem" type="button" className="min-h-10 w-full rounded px-2 text-left text-sm hover:bg-bg-hover">Preferências do perfil</button><button role="menuitem" type="button" className="min-h-10 w-full rounded px-2 text-left text-sm hover:bg-bg-hover">Sair da demonstração</button></div> : null}</div></header>; }
