"use client";
import { Menu, X } from "lucide-react";
import { usePathname } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { NavigationItem } from "@/components/layout/navigation-item";
import { DemoBadge } from "@/components/shared/demo-badge";
import { UnitSelector } from "@/components/app-shell/unit-selector";
import { demoNavigation } from "@/lib/demo/navigation";

export function DemoMobileDrawer() { const [open, setOpen] = useState(false); const pathname = usePathname(); const triggerRef = useRef<HTMLButtonElement>(null); const panelRef = useRef<HTMLDivElement>(null); const close = () => { setOpen(false); requestAnimationFrame(() => triggerRef.current?.focus()); }; useEffect(() => { setOpen(false); }, [pathname]); useEffect(() => { if (!open) return; const overflow = document.body.style.overflow; document.body.style.overflow = "hidden"; panelRef.current?.querySelector<HTMLElement>("a")?.focus(); const onKeyDown = (event: KeyboardEvent) => { if (event.key === "Escape") close(); if (event.key !== "Tab" || !panelRef.current) return; const items = [...panelRef.current.querySelectorAll<HTMLElement>('a,button:not([disabled])')]; const first = items[0]; const last = items.at(-1); if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); } }; document.addEventListener("keydown", onKeyDown); return () => { document.body.style.overflow = overflow; document.removeEventListener("keydown", onKeyDown); }; }, [open]); return <><button ref={triggerRef} type="button" aria-label="Abrir menu principal" aria-expanded={open} onClick={() => setOpen(true)} className="flex h-11 w-11 items-center justify-center rounded-md hover:bg-bg-hover lg:hidden"><Menu aria-hidden="true" size={20} /></button>{open ? <div className="fixed inset-0 z-50"><button type="button" aria-label="Fechar menu" onClick={close} className="absolute inset-0 bg-bg/80 backdrop-blur-sm" /><div ref={panelRef} role="dialog" aria-modal="true" aria-label="Menu principal" className="absolute inset-y-0 left-0 flex w-[min(20rem,88vw)] flex-col border-r border-line bg-bg-alt shadow-subtle"><header className="flex items-center justify-between p-4"><span className="font-display text-2xl">Flip<span className="text-primary">Schedule</span></span><button type="button" aria-label="Fechar menu principal" onClick={close} className="flex h-11 w-11 items-center justify-center rounded-md"><X aria-hidden="true" size={20} /></button></header><div className="space-y-3 px-3"><DemoBadge /><p className="text-sm font-medium">Clínica Aurora</p><UnitSelector /></div><nav aria-label="Principal" className="mt-4 flex-1 space-y-1 overflow-y-auto px-2">{demoNavigation.map((item) => <NavigationItem key={item.href} item={item} onNavigate={close} />)}</nav></div></div> : null}</>; }
