import "server-only";
import {getRuntimeEnvironment,isSecureRuntimeEnvironment,type RuntimeEnvironment} from "./environment";
export {getRuntimeEnvironment,isSecureRuntimeEnvironment,runtimeEnvironmentSchema} from "./environment";
export type {RuntimeEnvironment} from "./environment";
export type ExternalEffectsMode="DISABLED"|"SANDBOX";
export class RuntimeConfigurationError extends Error{override name="RuntimeConfigurationError";constructor(public readonly code="RUNTIME_CONFIGURATION_INVALID"){super("A configuração operacional não está disponível.")}}
export const isProductionRuntime=(env:Record<string,string|undefined>=process.env)=>getRuntimeEnvironment(env)==="production";
export const isStagingRuntime=(env:Record<string,string|undefined>=process.env)=>getRuntimeEnvironment(env)==="staging";
export function getExternalEffectsMode(env:Record<string,string|undefined>=process.env):ExternalEffectsMode{const value=env.EXTERNAL_EFFECTS_MODE?.trim()??"DISABLED";if(value!=="DISABLED"&&value!=="SANDBOX")throw new RuntimeConfigurationError();if(getRuntimeEnvironment(env)==="production"&&value==="SANDBOX")throw new RuntimeConfigurationError();return value}
export function getPublicApplicationOrigin(env:Record<string,string|undefined>=process.env){const secure=isSecureRuntimeEnvironment(env),raw=env.NEXT_PUBLIC_APP_URL??env.PUBLIC_APP_ORIGIN??env.BETTER_AUTH_URL;if(!raw){if(secure)throw new RuntimeConfigurationError();return new URL("http://localhost:3000")}try{const url=new URL(raw);if(secure&&url.protocol!=="https:")throw 0;return url}catch{throw new RuntimeConfigurationError()}}
export function requireRuntimeSecretReference(name:string,minLength=24,env:Record<string,string|undefined>=process.env){const value=env[name]?.trim();if(!value||value.length<minLength)throw new RuntimeConfigurationError("RUNTIME_SECRET_UNAVAILABLE");return value}
export function validateRuntimeConfiguration(env:Record<string,string|undefined>=process.env){const issues:string[]=[];let environment:RuntimeEnvironment;try{environment=getRuntimeEnvironment(env)}catch{return{environment:null,valid:false,issues:["APP_ENV_INVALID"] as string[]}}try{getPublicApplicationOrigin(env)}catch{issues.push("PUBLIC_ORIGIN_INVALID")}try{getExternalEffectsMode(env)}catch{issues.push("EXTERNAL_EFFECTS_MODE_INVALID")}
 if(isSecureRuntimeEnvironment(env)){const required=environment==="staging"?["NEXT_PUBLIC_APP_URL","BETTER_AUTH_URL","BETTER_AUTH_TRUSTED_ORIGINS","BETTER_AUTH_SECRET","DATABASE_URL","DIRECT_DATABASE_URL","FIELD_ENCRYPTION_KEY","RATE_LIMIT_HASH_KEY","OPERATIONAL_MODE","EXTERNAL_EFFECTS_MODE","ASAAS_ENVIRONMENT"]:["DATABASE_URL","BETTER_AUTH_SECRET","RATE_LIMIT_HASH_KEY"];for(const key of required)if(!env[key]?.trim())issues.push(`${key}_MISSING`);const secret=env.BETTER_AUTH_SECRET?.trim();if(!secret||secret.length<32||["dev-only-secret","change-me","example-secret"].includes(secret.toLowerCase()))issues.push("BETTER_AUTH_SECRET_INVALID");if(secret&&(secret===env.FIELD_ENCRYPTION_KEY?.trim()||secret===env.RATE_LIMIT_HASH_KEY?.trim()||env.FIELD_ENCRYPTION_KEY?.trim()===env.RATE_LIMIT_HASH_KEY?.trim()))issues.push("SECRETS_NOT_DISTINCT");try{const base=new URL(env.BETTER_AUTH_URL!);const origins=(env.BETTER_AUTH_TRUSTED_ORIGINS??"").split(",").filter(Boolean).map(x=>new URL(x.trim()));if(base.protocol!=="https:"||!origins.length||origins.some(x=>x.protocol!=="https:"||x.pathname!=="/"||x.search||x.hash||x.username||x.password||x.hostname==="localhost")||!origins.some(x=>x.origin===base.origin))throw 0}catch{issues.push("AUTH_ORIGINS_INVALID")}}
 if(environment==="staging"&&(env.ASAAS_ENVIRONMENT??"").toLowerCase()!=="sandbox")issues.push("ASAAS_PRODUCTION_DENIED");if(env.OPERATIONAL_MODE&&!new Set(["NORMAL","READ_ONLY","MAINTENANCE"]).has(env.OPERATIONAL_MODE))issues.push("OPERATIONAL_MODE_INVALID");if(env.PILOT_MODE==="true"&&!env.PILOT_TENANT_SLUGS?.trim())issues.push("PILOT_ALLOWLIST_EMPTY");return{environment,valid:issues.length===0,issues}}
