import "server-only";
import { z } from "zod";
export type RuntimeEnvironment="development"|"test"|"preview"|"staging"|"production";
export class RuntimeConfigurationError extends Error { override name="RuntimeConfigurationError"; constructor(public readonly code="RUNTIME_CONFIGURATION_INVALID"){super("A configuração operacional não está disponível.")} }
export function getRuntimeEnvironment(env:Record<string,string|undefined>=process.env):RuntimeEnvironment { const value=env.APP_ENV??env.NODE_ENV??"development"; return z.enum(["development","test","preview","staging","production"]).catch("development").parse(value); }
export const isProductionRuntime=(env:Record<string,string|undefined>=process.env)=>getRuntimeEnvironment(env)==="production";
export function getPublicApplicationOrigin(env:Record<string,string|undefined>=process.env){const raw=env.PUBLIC_APP_ORIGIN??env.BETTER_AUTH_URL;if(!raw){if(isProductionRuntime(env))throw new RuntimeConfigurationError();return new URL("http://localhost:3000")}try{const url=new URL(raw);if(isProductionRuntime(env)&&url.protocol!=="https:")throw new Error();return url}catch{throw new RuntimeConfigurationError()}}
export function requireRuntimeSecretReference(name:string,minLength=24,env:Record<string,string|undefined>=process.env){const value=env[name]?.trim();if(!value||value.length<minLength)throw new RuntimeConfigurationError("RUNTIME_SECRET_UNAVAILABLE");return value}
export function validateRuntimeConfiguration(env:Record<string,string|undefined>=process.env){const environment=getRuntimeEnvironment(env);const issues:string[]=[];try{getPublicApplicationOrigin(env)}catch{issues.push("PUBLIC_ORIGIN_INVALID")}if(environment==="production"){for(const key of ["DATABASE_URL","BETTER_AUTH_SECRET","RATE_LIMIT_HASH_KEY"] as const)if(!env[key]?.trim())issues.push(`${key}_MISSING`);if(env.ASAAS_BASE_URL?.includes("sandbox"))issues.push("ASAAS_ENVIRONMENT_MIXED")}if(env.OPERATIONAL_MODE&&!new Set(["NORMAL","READ_ONLY","MAINTENANCE"]).has(env.OPERATIONAL_MODE))issues.push("OPERATIONAL_MODE_INVALID");if(env.PILOT_MODE==="true"&&!env.PILOT_TENANT_SLUGS?.trim())issues.push("PILOT_ALLOWLIST_EMPTY");return {environment,valid:issues.length===0,issues};}
