import { validateSmokeTarget } from "./ops-smoke";

const MAX_BODY=1_000_000,TIMEOUT_MS=15_000;
export function assertSessionCookie(header:string){if(!/;\s*Secure(?:;|$)/i.test(header)||!/;\s*HttpOnly(?:;|$)/i.test(header))throw new Error("SMOKE_SESSION_COOKIE_INSECURE");return header.split(";",1)[0]!;}
export function assertSameOriginRedirect(base:URL,location:string|null){if(!location)throw new Error("SMOKE_REDIRECT_DENIED");const target=new URL(location,base);if(target.origin!==base.origin)throw new Error("SMOKE_REDIRECT_DENIED");return target;}
async function bounded(response:Response){const declared=Number(response.headers.get("content-length")??0);if(declared>MAX_BODY)throw new Error("SMOKE_RESPONSE_TOO_LARGE");const body=await response.text();if(body.length>MAX_BODY)throw new Error("SMOKE_RESPONSE_TOO_LARGE");return body;}
export async function runAuthenticatedSmoke(base:URL,email:string,password:string,fetcher:typeof fetch=fetch){
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),TIMEOUT_MS);let cookie="";const call=async(path:string,init:RequestInit={})=>{const response=await fetcher(new URL(path,base),{...init,redirect:"manual",signal:controller.signal,headers:{...init.headers,...(cookie?{cookie}:{})}});if([301,302,303,307,308].includes(response.status))assertSameOriginRedirect(base,response.headers.get("location"));return response};
 try{const login=await call("/api/auth/sign-in/email",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,password})});if(!login.ok)throw new Error("SMOKE_LOGIN_FAILED");cookie=assertSessionCookie(login.headers.get("set-cookie")??"");const tenant=process.env.PILOT_TENANT_SLUG?.trim();if(!tenant)throw new Error("PILOT_TENANT_REQUIRED");for(const path of [`/${tenant}`,`/${tenant}/agenda`,`/${tenant}/crm`,`/${tenant}/pacientes`,`/${tenant}/orcamentos`,`/${tenant}/inbox`,`/${tenant}/relatorios`,`/${tenant}/configuracoes`]){const response=await call(path);if(!response.ok)throw new Error("SMOKE_AUTHENTICATED_ROUTE_FAILED");const body=await bounded(response);if(path===`/${tenant}`&&!body.includes("AMBIENTE DE HOMOLOGAÇÃO"))throw new Error("SMOKE_PILOT_BANNER_MISSING");}const control=process.env.STAGING_CONTROL_TENANT_SLUG?.trim();if(control){const response=await call(`/${control}`);if(response.ok)throw new Error("SMOKE_CONTROL_TENANT_ALLOWED");}await call("/api/auth/sign-out",{method:"POST"});return {status:"PASSED",routesChecked:8,logout:true};}finally{clearTimeout(timer);cookie="";}
}
async function main(){const base=validateSmokeTarget(process.env.BASE_URL??"",process.env.STAGING_ALLOWED_HOSTNAME??"",process.env.PRODUCTION_HOSTNAME);const email=process.env.STAGING_SYNTHETIC_USER_EMAIL?.trim(),password=process.env.STAGING_SYNTHETIC_USER_PASSWORD;if(!email?.endsWith("@example.test")||!password)throw new Error("SYNTHETIC_CREDENTIALS_REQUIRED");console.info(JSON.stringify(await runAuthenticatedSmoke(base,email,password)));}
if(import.meta.url===`file://${process.argv[1]}`)main().catch((error:unknown)=>{console.error(error instanceof Error&&/^[A-Z0-9_]+$/.test(error.message)?error.message:"AUTHENTICATED_SMOKE_FAILED");process.exitCode=1});
