import { randomUUID } from "node:crypto";
import { getPrismaClient } from "../lib/db";
import { AsaasBillingAdapter } from "../domains/infrastructure/billing/asaas-billing-adapter";
import { AsaasHttpClient } from "../domains/infrastructure/billing/asaas-http-client";
import { AsaasBillingReconciliationService } from "../domains/infrastructure/billing/reconciliation-service";
import { EnvironmentCredentialStore } from "../domains/infrastructure/integrations/credential-store";
import { assertSafeWorkerEnvironment } from "../domains/infrastructure/integrations/runtime-guard";
import { sanitizeErrorCode } from "../domains/application/platform/privacy";
export async function main(limit=20){assertSafeWorkerEnvironment();const prisma=getPrismaClient(),rows=await prisma.subscription.findMany({where:{provider:"ASAAS",externalSubscriptionId:{not:null},status:{in:["PENDING","ACTIVE","PAST_DUE","SUSPENDED"]}},select:{id:true,tenantId:true},take:Math.min(20,Math.max(1,limit)),orderBy:{updatedAt:"asc"}});let reconciled=0,failed=0;const errors:{id:string;code:string}[]=[];for(const row of rows){try{const integration=await prisma.integration.findFirst({where:{tenantId:row.tenantId,provider:"ASAAS",status:"CONNECTED"},select:{credentialReference:true}});if(!integration?.credentialReference)throw new Error("CREDENTIAL_UNAVAILABLE");const credentials=await new EnvironmentCredentialStore().resolve(integration.credentialReference),key=credentials?.values.primary;if(!key)throw new Error("CREDENTIAL_UNAVAILABLE");await new AsaasBillingReconciliationService(prisma,new AsaasBillingAdapter(new AsaasHttpClient({accessToken:key,environment:"sandbox"}))).reconcile(row.tenantId,row.id,randomUUID());reconciled++}catch(error){failed++;const code=sanitizeErrorCode(error instanceof Error?error.message:undefined);errors.push({id:row.id,code});await prisma.subscription.updateMany({where:{id:row.id,tenantId:row.tenantId},data:{lastSyncedAt:new Date()}})}}return {scanned:rows.length,reconciled,failed,errors}}
if(import.meta.url===`file://${process.argv[1]}`)main().then(result=>console.info(JSON.stringify(result))).catch(()=>{console.error("Reconciliação de billing falhou.");process.exitCode=1})
