import type { PrismaClient } from "../generated/prisma/client";
import { getPrismaClient } from "../lib/db/client";
import { resolveExternalStagingIdentity } from "../lib/runtime/external-staging";
import { seedSyntheticStaging } from "./seed-staging";
import { hashPassword } from "better-auth/crypto";

export function assertExternalPilotSeed(env:Record<string,string|undefined>=process.env){const identity=resolveExternalStagingIdentity(env);if(env.SEED_CONFIRMATION!=="SEED_SYNTHETIC_EXTERNAL_STAGING")throw new Error("SEED_CONFIRMATION_REQUIRED");if(!identity.pilotMode||identity.pilotDataMode!=="SYNTHETIC_ONLY"||identity.externalEffectsMode!=="DISABLED")throw new Error("SYNTHETIC_PILOT_CONTRACT_REQUIRED");const slug=env.PILOT_TENANT_SLUG?.trim();if(!slug||!(env.PILOT_TENANT_SLUGS??"").split(",").map(x=>x.trim()).includes(slug))throw new Error("PILOT_TENANT_DENIED");return slug;}
export async function seedExternalStagingPilot(prisma:PrismaClient,env:Record<string,string|undefined>=process.env){const slug=assertExternalPilotSeed(env),email=env.STAGING_SYNTHETIC_USER_EMAIL?.trim().toLowerCase(),password=env.STAGING_SYNTHETIC_USER_PASSWORD;if(!email?.endsWith("@example.test")||!password||password.length<16)throw new Error("STAGING_SYNTHETIC_CREDENTIALS_REQUIRED");const seeded=await seedSyntheticStaging(prisma,slug),tenant=await prisma.tenant.findUniqueOrThrow({where:{slug},select:{id:true}}),passwordHash=await hashPassword(password);const user=await prisma.user.upsert({where:{emailNormalized:email},create:{emailNormalized:email,displayName:"[SINTÉTICO] Operador de smoke",emailVerified:true,emailVerifiedAt:new Date()},update:{displayName:"[SINTÉTICO] Operador de smoke"},select:{id:true}});await prisma.membership.upsert({where:{tenantId_userId:{tenantId:tenant.id,userId:user.id}},create:{tenantId:tenant.id,userId:user.id,role:"OWNER",status:"ACTIVE",acceptedAt:new Date()},update:{role:"OWNER",status:"ACTIVE"}});await prisma.authAccount.upsert({where:{providerId_accountId:{providerId:"credential",accountId:user.id}},create:{providerId:"credential",accountId:user.id,userId:user.id,password:passwordHash},update:{password:passwordHash}});return {...seeded,datasetProfile:"EXTERNAL_STAGING_PILOT",syntheticSmokeAccountEnsured:true};}
async function main(){const prisma=getPrismaClient();try{console.info(JSON.stringify(await seedExternalStagingPilot(prisma)))}finally{await prisma.$disconnect()}}
if(import.meta.url===`file://${process.argv[1]}`)main().catch((error:unknown)=>{console.error(error instanceof Error&&/^[A-Z0-9_]+$/.test(error.message)?error.message:"EXTERNAL_STAGING_SEED_FAILED");process.exitCode=1});
