export const SESSION_IDLE_TIMEOUT_SECONDS = 60 * 60;
export const SESSION_REFRESH_INTERVAL_SECONDS = 5 * 60;

export const SESSION_IDLE_TIMEOUT_MS = SESSION_IDLE_TIMEOUT_SECONDS * 1000;
export const SESSION_REFRESH_INTERVAL_MS = SESSION_REFRESH_INTERVAL_SECONDS * 1000;

export const SESSION_ACTIVITY_STORAGE_KEY = "flipschedule:last-session-activity";
